# Introduction
<!-- Scientific name, distribution, the basis for the choice of stock structure, including regional differences in life history or other biological characteristics that should form the basis of management units. A map showing the scope of the assessment and depicting boundaries for fisheries or data collection strata.  -->

Yellowtail rockfish, *Sebastes flavidus*, occur off the West Coast of the United States from Baja California to the Aleutian Islands.  Yellowtail is a major commercial species, captured mostly in trawls from Central California to British Columbia [@Love2011].  Because it is an aggregating, midwater species it is usually caught in the commercial midwater trawl fishery. In California there is a large recreational fishery as well. The center of Yellowtail rockfish abundance is from southern Oregon through British Columbia [@Fraidenburg1980]. We briefly summarize Yellowtail rockfish life history, fisheries, assessment and management here, but in-depth, extensive background information on Yellowtail rockfish and other managed species is available at [@PFMC2024].  

A previous genetic study [@Hess2011] indicates that there are in fact two stocks of Yellowtail rockfish, with a genetic line at Cape Mendocino, California, roughly $40^\circ 10^\prime$ North Latitude.  This study of 1013 fish from 21 sites along the West Coast from Mexico through Alaska examined two datasets, one of mitochondrial DNA, and one of nuclear DNA microsattelite loci. Findings in both datasets agreed, and also concur with the findings of Field and Ralston [-@Field2005] who looked at differences in recruitment trends related to physical forcing and coherence along the coast, and found the greatest differences among the U.S. and Canadian stocks to be defined by Cape Mendocino. Neither the genetic study nor the oceanographic studies definitively identify mechanisms of stock isolation; however, they suggest that a combination of physical forcing due to offshore advection and differences in available habitat across Cape Mendocino may together account for the differences observed.

A map showing the scope of the assessment and depicting boundaries for fisheries or data collection strata is provided in @fig-assessregionmap. The 2017 Yellowtail rockfish assessment was the first full length and age integrated assessment south of Cape Mendocino, though the southern model was not accepted for use in management. Here we assess only the northern stock in @fig-assessregionmap.

## Life History
<!-- Important features of life history that affect management (e.g., migration, sexual dimorphism, bathymetric demography).   -->

Rockfish are in general long-lived and slow-growing; however, Yellowtail rockfish have a high growth rate relative to other rockfish species, reaching a maximum size of about 55 cm in approximately 15 years [@Tagart1991].  Yellowtail are reported to live at least 64 years [@Love2011], but no fish that old occur in data available for this assessment (the 95th percentile of age is 35 years for females and 45 years for males).  The maximum age plausibly observed  is 60. There were additional data we considered to be outliers. For example, three fish in the commercial data were reported to be 70, 99, and 101.

Yellowtail rockfish are among those that are fertilized internally and release live young.  Spawning aggregations occur in the fall, and parturition in the winter and spring (January-May) [@Eldridge1991].  Young-of-the-year recruit to nearshore waters from April through August, migrating to deeper water in the fall.  Preferred habitat is the midwater over reefs and boulder fields. Young-of-the-year Yellowtail rockfish settle to nearshore areas, and are known to utilize kelp bed habitat [@Love2011]. @laidig2023distribution note that young yellowtail are found in kelp beds but also in slightly deeper waters seaward of kelp beds.   

Yellowtail rockfish are extremely motile, and make rapid and frequent ascents and descents of 40 meters; they also exhibit strong homing tendencies [@Love2011].  They are able to quickly release gas from their swim bladders, perhaps making them less susceptible to barotrauma than similar species [@Eldridge1991].  

## Ecosystem considerations
<!-- Ecosystem considerations that include relevant information on how environmental drivers, prey, competition, predation, and/or (habitat requirements/preferences may affect stock’s status, vital rates (growth, survival, productivity, recruitment), or range and distribution. Ecosystem considerations may also include how these factors, cross-FMP interactions with other fisheries and human social dynamics that may affect the stock (e.g., reliance and dependence by fishing communities, non-target species constraining harvest rates). The length and depth of this section will depend on availability of information from published studies and Integrated Ecosystem Assessment reports, expertise of the STAT, and whether ecosystem factors contribute quantitative information to the assessment. This is not required for an update assessment if a citation to the previous assessment is provided.  -->

A number of studies correlate environmental conditions to pelagic juvenile abundance and juvenile recruitment of rockfishes, including Yellowtail rockfish. Year-class strength is particularly impacted during the early larval phase, and annual pelagic juvenile abundance is correlated with physical conditions, especially upwelling strength along the coast [e.g., @Field2005; @Laidig2007; @Laidig2010; @Ralston2013]. Rockfish in general are sensitive to the strength and timing of the upwelling cycle in the Eastern Pacific, which affects where pelagic juveniles settle, and impacts the availability of the zooplankton which the young require.

Yellowtail rockfish feed mainly on pelagic animals, but are opportunistic, occasionally eating benthic animals as well. Large juveniles and adults eat fish (small Pacific Whiting, Pacific Herring, smelt, anchovies, lanternfishes, and others), along with squid, krill, and other planktonic organisms. @Wippel2017 summarized diet data for Yellowtail rockfish based on 1069 stomachs collected from 1982 - 1999. Ranked from most to least common, the dominant prey were *euphasiids* (krill), juvenile hake, gelatinous zooplankton (predominantly salps and ctenophores) and herring. For juvenile yellowtail, the dominant prey taxa were *euphasiids* and mesozooplankton such as copepods.

Yellowtail rockfish are prey for Chinook Salmon, Lingcod, Cormorants, Pigeon Guillemots and Rhinoceros Auklets [@Love2011]. Based on Ecopath foodweb modeling, seven  predators are identified as high sources of predation mortality: California sea lions, lingcod, porpoises, fur seals, harbor seals, sablefish and skates. 

## Fishery description
<!-- Important features of current fishery and relevant history of fishery.  -->

The rockfish fishery off the U.S. Pacific coast first developed off California in the late 19th century as a hook-and-line fishery [@Love2002]. The first record of Yellowtail in a catch reconstruction is commercial catch in Washington in 1889; Oregon has a record shortly thereafter in 1892. Records for recreational fishing begin in 1928. The rockfish trawl fishery was established in the early 1940s, when the United States became involved in World War II and wartime shortage of red meat created an increased demand for other sources of protein [@Alverson1964; @Harry1961; @Miller2014].

During the early development period of the rockfish fishery there was little attention paid to quantifying the species composition of the landings. It wasn't until the early 1960s that coastal states began to report landings by species [@Niska1976; @TagartKimura1982]. Nonetheless, we do know that Yellowtail rockfish were a part of the fishery. For example, @Phillips1964 reports that prior to the 1940s, Yellowtail rockfish were predominant in commercial catches in northern and central California. Similarly, @AlversonWelander1952 report Yellowtail rockfish among the primary species landed in Washington during World War II. Although we know Yellowtail rockfish were caught during this time, we have no substantive knowledge of the proportion of their contribution to the total landings.

Between 1967 and 1974, there was a steady but low-level fishery in the Columbia area, primarily prosecuted by Oregon based fishermen. By 1975, an increasing number of U.S. fishermen had begun to prospect fishing grounds along the south central Washington coast. In 1977, the U.S. extended fisheries jurisdiction to 200 nautical miles offshore. Yellowtail rockfish off Oregon and Washington were an important target of the expanding fishery in the late 1970's and 1980's. The development of the Yellowtail rockfish fishery provoked improvements in fishing strategies and fishing gear, such as three-seam, triplebridle trawls to increase the vertical opening of the net, and improvements in roller gear needed to access rockfish habitat. 

In the 1980s and 1990s, midwater trawl was used to harvest widow, yellowtail, and chilipepper rockfish. New technology extended fishing operations into previously unfished areas and enabled vessels to follow widow rockfish concentrations throughout the year [@Quirollo1987; @Demory1987]. Yellowtail rockfish were harvested as part of a directed mid-water trawl fishery, with fairly high landings in the 1980s and 1990s. As a midwater species, it is also a commonly caught as bycatch in the hake fishery.

Today, Yellowtail are predominantly caught with trawl gear, though a recreational fishery also exists. Yellowtail commonly co-occur with a number of rockfish species, especially Canary and Widow rockfish [@Tagart1988; @Rogers1992]. The overfished declarations of both species, and others, around 2000 substantially altered fishing opportunities for Yellowtail. In order to achieve the necessary reduction in the catch of Canary rockfish, Widow rockfish and other overfished species, stringent management measures were adopted, limiting harvest of Yellowtail rockfish as well as other co-occurring species.

Canary was declared rebuilt in 2015 [@thorson_status_2015], and commercial and recreational Yellowtail catch increased substantially beginning when that assessment was first used for harvest specifications in 2017. Widow had already been declared rebuilt at that time.

## Management History
<!---
Summary of management history (e.g., changes in mesh sizes, trip limits, or other management actions that may have significantly altered selection, catch rates, or discards). 
--->

Yellowtail rockfish are currently managed with stock-specific harvest specifications north of $40^\circ 10^\prime$ N. latitude, and as part of the Southern Shelf rockfish complex south of $40^\circ 10^\prime$ N. latitude.

Prior to 1983, the domestic trawl fishery for Yellowtail rockfish was constrained only by market forces. In 1983, U.S. managers imposed a 40,000 lb trip limit on landings from the *Sebastes* complex (an collection of rockfish species that included Yellowtail rockfish). In addition to trip limits, the PFMC set a harvest guideline (HG), or target quota, for the complex. By September 1983, harvest was approaching the quota (18,500 mt) in Columbia and Vancouver areas. Managers responded by reducing the trip limit to 3,000 lbs and requiring fishers not to exceed one trip per week. This began a tumultuous management history for Sebastes complex species and Yellowtail rockfish in particular [@Tagart2000]. 

Constraints on Yellowtail rockfish landings by controls on the Sebastes complex were replaced in 1985 with direct limits on Yellowtail rockfish. The Council used trip limits and trip frequency regulations in an attempt to spread the harvest throughout a calendar year, reduce bycatch in the directed fishery and limit regulatory induced discard. In-season adjustments, usually reductions, to the limits have occurred frequently [@Tagart2000]. From 1985 to 1991 trip limits were changed often. Managers attempted to provide flexibility for individual harvests by devising weekly, bi-weekly and twice weekly trip limit options. Increasing harvest rates and declining abundance of coastal groundfish species subsequently resulted in smaller and smaller trip limits. Yellowtail weekly trip limits diminished from a high of 12,500 lbs mid-1986 to a weekly equivalent of 2,500 lbs in 1991

From the inception of regulation in 1993, through 1999, Yellowtail rockfish were managed as part of the Sebastes complex. In 2000, the Council adopted a new partitioning of rockfish species, abandoning the former complex. At that time, South of Cape Mendocino, Yellowtail rockfish was assigned to the Minor Shelf rockfish group; north of Cape Mendocino, was managed as a single species. 

In 1999, Yellowtail rockfish bycatch in the whiting fishery closed the directed fishery for Yellowtail rockfish for the last three months of the year in order to remain within the optimum yield. Yellowtail rockfish co-occur with canary, widow, and several other rockfishes [@Nagtegaal1983; @Tagart1987; @RogersPikitch1992]. Association with other rockfish species has substantially altered fishing opportunity for Yellowtail rockfish. Canary rockfish stocks were determined to be overfished in 2000. In order to achieve the necessary reduction in the canary rockfish catch, the Council adopted stringent management measures starting in 2000. Harvest of canary rockfish and their co-occurring species was limited. 

Beginning in 2000, shelf rockfish species could no longer be retained by vessels using bottom trawl footropes with a diameter greater than 8 inches. The use of small footrope gear increases the risk of gear loss in rocky areas. This restriction was intended to provide an incentive for fishers to avoid high-relief, rocky habitat, thus reducing the exposure of many depleted species to trawling. This was reinforced through reductions in landing limits for most shelf rockfish species.

Since September 2002, trawl and non-trawl rockfish Conservation Areas (RCAs, areas known to be critical habitat) have been closed to fishing.  Alongside these closures, limits on landings were put in place that were designed so as to accommodate incidental bycatch only. These eliminated directed mid-water fishing opportunities for Yellowtail rockfish in non-tribal trawl fisheries and increased discard rates (which had historically been low). A somewhat greater opportunity to target Yellowtail rockfish in the trawl fishery became available in 2011 under the trawl rationalization program. However, quotas for Widow and Canary rockfish generally constrained targeting of Yellowtail rockfish. This changed with the rebuilding declaration of Canary rockfish in 2015 (with increases in catch limits beginning in 2017), as well as new exempted fishing permits for midwater trawl gear in 2017-2018. In addition, a number of updates to regulations around trawl and non-trawl RCAs from 2019-2024 further expanded opportunities to fish in abundant Yellowtail habitat.

While recreational fisheries have caught Yellowtail for many years, recent exempted fishing permits for Holloway longleader gear in Oregon and limited bag limits for Black rockfish in Washington have pushed recreational fisheries farther offshore and increased the sizes and amount of Yellowtail caught in the recreational sector.  

## Management performance
<!-- Management performance, including a table or tables comparing Overfishing Limit (OFL), Acceptable Biological Catch (ABC), Annual Catch Limit (ACL), landings, and catch (i.e., landings plus discard) for each area and year. Groundfish assessments that estimate dead discarded catch must include a disclaimer noting that total mortality estimates from the WCGOP and from the stock assessment may differ due to the use of different methods. Investigation into how these methods differ is beyond the scope of a benchmark assessment. The rationale for modeling discard mortality can also be provided. This should be included in all update assessments.  -->

<!-- Marlene might have the info we need? Look at what Chantel has for sablefish -->

<!-- Megan pulled this from old assessment in 2000 can get rid of it if we want -->

Between 1983 and 2000, annual estimated catch has averaged 51% greater than the harvest guideline. Total catch always exceeded the assessment’s low estimate of ABC and has exceeded the high ABC 44%. However, between 1995 and 2000 total has exceeded the Council ABC’s an average of only 24% of the time [@Tagart2000].

Over the past decade, catch has remained substantially below ACL (Table \ref{tbl-es-management}). Total catch (including landings and discards) doubled between 2016 and 2017 but still remained less than 50% of the ACL. Total catch has remained well below the management limits and harvest specifications in recent years (Table \ref{tbl-es-management})

## Fisheries off Canada and Alaska

<!-- Description of fisheries for this species off Canada, Alaska and/or Mexico, including references to any recent assessments of those stocks extending beyond the Council’s jurisdiction. STATs are strongly encouraged to include a summary of catches and estimates of stock size and stock status for the most recent ten years if such information can be assembled without excessive difficulty. This is not required for an update assessment.    -->

<!-- See if AK has a more up to date assessment (MF) and add updated information on the Canada Assessment (IT) -->

Yellowtail rockfish are a target species in Canada with catches between 4000-6000 mt since the late 1980s. It has the second largest single-species Total Allowable Catch (TAC) among rockfish species under quota management for the Canadian Pacific Coast. In Canada it is caught in similar amounts by bottom and midwater trawl gear. A 2015 stock assessment conducted by the Fisheries and Oceans Canada found the stock to be at 50\% of unfished spawning biomass, in the "healthy" range [@DFO2015]. 

A new Canadian assessment was reviewed in October 2024 but has not yet been published. This model also used SS3 but was purely age-based with an empirical weight-at-age matrix used instead of parametric growth. Management quantities were also based on posterior medians rather than maximum likelihood estimates. However, for purposes of comparison with the current base model, the MLE estimates from model files available at https://github.com/pbs-software/pbs-synth/blob/master/PBSsynth/inst/input/2024/YTR were used to compare results with the base model. The time series of fraction unfished is similar as are the recruitment deviations (@fig-can-timeseries) suggesting that recruitment is linked between the two regions among other connection between these two stocks. The 1990, 2008, and 2008 cohorts are some of the largest in both model (@fig-can-recdevs).

The Alaska Fisheries Science Center assesses Yellowtail rockfish as one of 25 species in the "Other rockfish" complex in the Gulf of Alaska. The Other rockfish complex in the Gulf of Alaska (GOA) is assessed on a biennial stock assessment schedule to coincide with the availability of new trawl survey biomass estimates in odd years. The last operational full assessment was conducted in 2023 and an update assessment was conducted in 2024. There was no evidence to suggest that overfishing is occurring for the Other rockfish stock complex in the GOA because the OFL has not been exceeded. Total Other rockfish catch in 2023 was 1,079 t was lower than the Gulf-wide OFL and ABC of 4,054 t and 3,774 t, respectively [@Omori2023; @Omori2024].
