# Data

<!--- Provide temporal and spatial resolutions or sample size where appropriate for each of the subsections, below.--->

A summary of available data by type and fleet is available in @fig-data.

## Fishery-dependent data

<!-- Commercial fisheries landings by state, year, and gear (PacFIN is the standard source for recent domestic commercial landings), historical catch estimates, discards, recreational fisheries catches, foreign removals; sample size information for length- and age-composition data by state, year and gear, including both the number of trips and fish sampled. Description of methods to estimate abundance indices, sample size information by survey and year. Include complete tables and figures and date of data extraction. -->

Fishery-dependent data were split into three fleets: a shoreside commercial fleet ("commercial"), an at-sea hake commercial fleet ("at-sea"), and a recreational fleet ("recreational"). The vast majority of catches across all years has come from trawl gear in the shoreside commercial sector.

### Landings

A summary of total removals are provided in @tbl-all_removals and @fig-catch. (KLO: I don't know why that is linking to Table i instead of Table 1! The text, not the link, is correct. This is an issue for tables 1-8, where the link goes to tables i-viii. I will try to resolve it this week.)

#### Commercial

Commercial landings ultimately came from a mix of \gls{pacfin} and state reconstructions.

\Gls{wdfw} provided a catch reconstruction from 1889 to 2000 (T. Tsou, WDFW, pers. comm.). The 2017 assessment used the same reconstruction [@stephens_status_2017]. The three main sources used in this reconstruction are from the U.S. Fish Commission Report (UFSC), Washington Bound Volumes, and Washington Statistical Bulletin. The historical species composition is based on the various historical reports and interviews of old-time fishermen and dockside samplers. The 1981 to 2000 landings are different from \gls{pacfin} records due to a revised approach for apportioning out unidentified rockfish (“URCK”) in fish tickets to the species level. The revised approach relaxed the borrowing rules for missing data currently used in the \gls{wdfw} species allocation algorithm [@Tsou2015]. Landings from 2001 to 2024 were downloaded from \gls{pacfin} (pulled March 10, 2025).

In Oregon, historical commercial landings from 1892 to 1986 were provided by \gls{odfw} [@karnowski_historical_2014]. Landings from 1987 – 1999 were compiled from a combination of \gls{pacfin} and a separate \gls{odfw} reconstruction that delineated species-specific landings in the unspecified categories on \gls{pacfin} [e.g. URCK and POP1, @ODFW_URCK_POP_recon]. Yellowtail rockfish landings from this reconstruction were substituted for the URCK and POP1 landings available from PacFIN and added to PacFIN landings from other categories for a complete time series during this time period. Commercial landings from 2000 – 2024 are available on \gls{pacfin}.

California commercial landings came from the reconstruction in @ralston_documentation_2010 and an additional reconstruction of catches off the coast of Oregon landed into California (J. Field, SWFSC, pers. comm.) during that time (1916-1968), \gls{calcom} (1969-1980), and \gls{pacfin} (1981-2024, pulled March 10, 2025). \Gls{calcom} and \gls{pacfin} data in California were filtered to include only the Eureka and Crescent City port area groups (equivalent to Humboldt and Del Norte counties) to approximate landings north of $40^{\circ} 10'$. While Shelter Cove is in Humboldt county but south of $40^{\circ} 10'$, and this approach assigns catch based on port of landing rather than geographic location of catch, this is the same approach used in the 2017 assessment. In conversations with \gls{cdfw}, it was determined to be the best way to identify catches for the northern stock given the available data.

In the @ralston_documentation_2010 reconstruction, the northernmost region (region 2) includes Crescent City, Eureka *and* Fort Bragg port area groups. Catch in the Crescent City and Eureka port area groups is estimated based on the fraction of catch in Crescent City and Eureka divided by catch in all of region 2 during the first five years of \gls{calcom} (1969-1973). The vast majority (96%) of the catch is in the two northern port areas. All supplementary catches in the reconstruction of catches off the coast of Oregon, but landed into California are included.

Foreign commercial landings caught in U.S. waters that occurred prior to closure of the EEZ are not included in any state historical reconstruction. Estimates of these landings were added to domestic commercial catches for 1966-1976 [@rogers_species_2003]. Note that these catches were missing from the 2017 assessment.

#### At-sea

At-sea catches from \gls{norpac} were provided by Vanessa Tuttle at \gls{nwfsc} on November 7, 2024 for the years 1976-2023, and on February 11, 2025 for 2024.

#### Recreational

Recreational landings came from a mix of \gls{recfin}, \gls{mrfss}, and state reconstructions. They are assumed to include both retained and released fish.

For Washington, historical catch estimates (1967-1970, 1972, 1973, and 1975-1989) and \gls{osp} estimates (1990-2024) are available in \gls{recfin} (pulled February 13, 2025). The historical catch estimates for 1971 and 1974 were not available in the historical report and were treated as the average of the two preceding and two following years. Historical data were filtered to marine catch areas 1-4. For \gls{osp} data, we used data in table CTE501 on \gls{recfin}, filtering out catches from Canada and those east of the Sekiu River ("Sekiu River and Pillar Point" catch area).

Washington's historical recreational catches are only available in numbers. Unlike in the 2017 assessment, we converted these these catches to weights before entering them into the model in order to facilitate a single recreational fleet. This seemed appropriate given that recreational catches across all three states represent a relatively small fraction of total fishing mortality (@fig-catch). To do this, we calculated average length of samples collected prior to 1990 in the WA Sport Biodata. This included 48 samples from 1979, 1981, and 1982. The next available samples were in 1995. We used an unsexed length-weight relationship calculated from survey data.

For Oregon, a historical reconstruction provided numbers of fish from 1979-2000 [@Whitman_2024], which were converted to biomass using biological samples from the \gls{mrfss} (A. Whitman, ODFW, pers. comm.). These landings in biomass were provided by ODFW. Recreational landings for Oregon from 2001-2024 are available from \gls{recfin}.

California recreational catches came from Ralston et al. [-@ralston_documentation_2010] (1928-1980), as well as \gls{mrfss} (1981-2004) and \gls{crfs} (2005-2024) estimates, both of which are available on \gls{recfin} (downloaded November 12, 2024 and February 21, 2025, respectively). For \gls{crfs}, only catches in the Redwoods district were considered to be part of the northern stock. Ralston et al. [-@ralston_documentation_2010] and \gls{mrfss} aggregate catches into Northern and and Southern California. \Gls{mrfss} excluded San Luis Obispo county from Northern California from 1980-1989 only. San Luis Obispo is included in Northern California in Ralston et al. [-@ralston_documentation_2010] and later years of \gls{mrfss}. Albin et al. [-@albin1993] estimated recreational catches in California by county from San Luis Obispo north from 1981-1986. We calculated 1) the ratio of catches in Albin et al. [-@albin1993] in Del Norte and Humboldt counties divided by the catch in *all* counties, 2) the ratio of catches in Albin et al. [-@albin1993] in Del Norte and Humboldt counties divided by the catch in all counties *except* San Luis Obispo, and 3) the ratio of total catch in \gls{crfs} in the Redwoods district divided by total catch in the Northern California sub-region from 2005-2010. Then, to calculate catches north of $40^{\circ}10'$, we multiplied total Northern California catches in Ralston et al. [-@ralston_documentation_2010] by ratio (1). From 1981-1989, we multiplied Northern California catches in \gls{mrfss} by ratio (2). From 1993-2004 we multiplied Northern California catches in \gls{mrfss} by a weighted average of ratios (1) and (3). Weights were the inverse of time to the last year in Albin et al. [-@albin1993] and the first year of \gls{crfs}. No \gls{mrfss} estimates are available from 1990-1992. For this time period, we interpolated between the average catches from 1987-1989 and 1993-1995.

### Discards

Discards were added to landings for the shoreside commericial fleet. For the years prior to 2002 when the \gls{wcgop} program began, landings were multiplied by 1.0451 based on an estimated discard ratio of 4.51% (J. Wallace pers. comm.) in @pikitch_evaluation_1988. For 2002-2023, discard amounts in metric tons were taken from the \gls{gemm} report. Because the \gls{gemm} report for 2024 mortality was not yet available, discards for 2024 were inadvertently left out of the base model. The mean discards over the period 2019-2023 were 5.3 mt per year and an exploration of the impact of adding these discards to the 2024 catches changed the fraction of unfished spawning output in 2025 by only 0.00005, but will be included in any future updates to the base model.

Explorations using the 2017 assessment model showed that the alternative discard treatments in the model had neglible impact on point estimates and uncertainty. Data exploration also indicated the sizes of discarded and retained fish were similar in years where discard composition data was available, so the consolidation of discards and landings seemed appropriate. The change simplifies the model by removing 13 estimated parameters. It also corrects an issue which led to overestimation of discard amounts in the 2017 assessment. Comparing discard estimates between the \gls{gemm} and the 2017 model revealed large discrepencies which were found to be related to differences between tribal and non-tribal discards. The discard rates estimated by \gls{wcgop} during the years 2004--2010 were estimated to be high (above 50% in some years), but only represent the non-tribal catch. During this same period, the tribal catch represented the majority of the commercial catch and the tribal fishery had full retention of yellowtail. Modeling retention appropriately would have required separating the tribal and non-tribal catch into separate fleets. <!-- 
# counting 13 retention parameters in 2017 model
model$parameters |> dplyr::filter(Phase > 0 & grepl("Ret", Label)) |> dplyr::pull(Label) 
-->

Historical recreational reconstructions do not include an estimate of discarded fish. Historical bag limits in the recreational fishery were generally liberal, and the assumption of full retention was deemed reasonable. Modern post-\gls{mrfss} recreational sampling programs incorporate estimates of discard mortality into total dead catch estimates, and these were used.

### Biological data

```{=html}
<!-- 
# calculations for table below (could be made dynamic in the future): 

# year range
rec_bio_table |> dplyr::pull(Year) |> range()
[1] 1980 2024

# total lengths
rec_bio_table |> dplyr::select(-Year, -Washington.ages) |> sum()
# [1] 64637

# percentages of lengths
rec_bio_table |> dplyr::select(-Year, -Washington.ages) |> apply(2, sum) |> prop.table() |> round(2)
Washington     Oregon California
      0.26       0.71       0.03

rec_bio_table |> dplyr::pull(Washington.ages) |> sum()
# [1] 9205
-->
```

Commercial biological samples were available from the three coastal states covering the years 1972--2024 (@tbl-comm_lengths, @tbl-comm_ages, @fig-len-all-bubbles, @fig-age-all-bubbles, first row). There were 197,400 length samples, of which 49% were from Washington, 47% from Oregon, and 4% from California (Humboldt and Crescent City port area groups only). There were 161,697 age samples, of which 49% were from Washington, 48% were from Oregon, and 2% were from California. Because most commercial length and age data was sexed, unsexed commercial biological samples were excluded. Sensitivity to excluding unsexed lengths (where most of the unsexed data existed) was explored. Input sample size was calculated based on a combination of the number of trips and number of individuals (I. Stewart, pers. comm.):

$$
N_\text{input} = 
\left\{
  \begin{array}{ll}
    N_\text{trips} + 0.138 N_\text{fish}, & \tfrac{N_\text{fish}}{N_\text{trips}} < 44 \\
    7.06 N_\text{trips}, & \text{otherwise}
  \end{array}
\right.
$$

Any year with less than 100 length samples was excluded to avoid the influence of sparse data. Commercial composition data were filtered ("expanded") using the {pacfintools} package maintained at the NWFSC, where expansions weighted individual samples based on the trip-level and state-level catches.

At-sea biological samples were available from 1976--2024 (@tbl-ashop_comps, @fig-len-all-bubbles, @fig-age-all-bubbles, second row). This includes 112,708 length samples across all years and 643 age samples from 2019 and 2023 (two recent years with particularly high yellowtail catches in the at-sea fishery). Virtually all data were sexed, so unsexed data were excluded. Input sample size was number of hauls ("tows").

Recreational biological samples were available from the three coastal states covering the years 1980--2024 (@tbl-rec-bio, @fig-len-all-bubbles, @fig-age-all-bubbles, third row). There were 64,637 length samples, of which 71% was from Oregon, 26% from Washington, and 3% from California (North of $40^{\circ} 10'$). There were 9,205 age samples, 100% of which were from Washington. Input sample size was number of fish. <!-- IMPACT OF SKEW OF REC AGES -->

### Abundance indices

Two fishery-dependent abundance indices were developed: one from commercial observer data and one from recreational sampling data. While neither index is in the base model, sensitivity to their inclusion is explored, and the standardization procedure is described here.

#### Commercial observer and electronic monitoring index

Yellowtail rockfish are a midwater rockfish often found slightly above the seafloor in rocky untrawlable habitat, and therefore standard bottom trawl surveys may not effectively measure changes in relative abundance. The commercial fishery often catches them using midwater trawl gear. Catch share vessels in the trawl fishery have had 100% observer or electronic monitoring (EM) coverage since 2012. We generated a fishery-dependent observer index using data from \gls{wcgop}, filtered to trips that used midwater gear, caught yellowtail, widow, or canary rockfish (i.e., the main midwater rockfish species), and for which \>50% of the catch was rockfish (i.e., not shoreside hake trips, where vessels may be actively avoiding rockfish). The data covered 2012-2023 and included 3,962 tows on 878 unique trips by 46 different vessels; 69.7% of tows contained yellowtail. Data from 2024 was not available by the data deadline. We used \gls{sdmtmb} to fit a delta-lognormal model [@Anderson_2024_SRP] to the catch per unit effort (metric tons caught per hour towed). In addition to fixed effects for each year, we included a spline term for standardized depth, a cyclic spline for month (i.e., forces a smooth transition from December to January), a fixed effect for observer versus EM data, a random effect for vessel ID, and a fixed effect for whether the tow was conducted north or south of the mouth of the Columbia River. During the pre-assessment workshop, fishermen reported catches of yellowtail are consistently much higher north of the Columbia River, which is corroborated in the survey data (@fig-wcgbts-map). We did not fit a full spatiotemporal model because tow locations are non-random, which can lead to bias [@conn2017confronting]. The main purpose of this index was to explore whether fishery catch rates using midwater gear are similar to or different from a fishery-independent bottom trawl survey index; in general the temporal patterns appear quite similar (@fig-wcgop). However, we did conduct a sensitivity to the inclusion of the index in the assessment model (@sec-sensitivities).

#### Oregon ORBS Dockside Index (2001 - 2024)

Trip-level catch-per-unit-effort data from \gls{orbs} dockside sampling was obtained from ODFW. The travel time was subtracted from the hours fished. Travel time was stratified by boat type (charter and private) and was calculated as the inverse of boat type-specific speeds (13 mph for charter boat trips and 18 mph for private boat trips) multiplied by twice the distance between the port of origin and the reef that was fished. Catch-per-unit-effort (CPUE), expressed in terms of fish per angler-hour, was calculated by multiplying the number of anglers and the adjusted travel time. The database contains information on catch by species (number of retained fish), effort (angler hours), sample location (port where data were collected), date, bag limits and other relevant regulations, boat type (charter or private), and trip type (e.g., bottom associated fish).

The unfiltered data set contained 456,172 trips from 2001 - 2024. We filtered out trips with incorrect interview times and unreasonably long or short trips. Only bottomfish target trips were included. Further filters excluded temporal or spatial fishing closures and catches exceeding bag limits. Trips from several ports with extremely small sample sizes (\<1% of total trips) and those that met criteria for irrational effort reporting (i.e., implausible values) or extreme catch rates were excluded as well. The final dataset included 137,502 trips, approximately 30% of the unfiltered sample size (@tbl-percent_pos).

We evaluated year, month, port, the open depths to fishing (all depths or inside 20/30/40fm), boat type and the daily bag limit for yellowtail rockfish in the standardization model. Preliminary model explorations indicated that the daily bag limit covariate could not be combined with the open depth of the fishery due to changes in recreational fishing regulations over time. Prior to 2017, yellowtail rockfish were included in the general marine bag limit. However, in 2017, yellowtail rockfish were also included in a specialized longleader recreational bag limit where participants were required to be seaward of 40fm. As a result, the bag limits were binned into a binary variable for low (5 – 8 fish) and high (10 – 15 fish) bag limits during the 2001 – 2024 time period. Negative binomial models were fit in \gls{sdmtmb} (Version 0.6.0) to the trip-level data (catch in numbers with a log offset for adjusted angler hours). Tweedie distributions were also explored for selected models but generally did not improve Q-Q plots. The final model selected by \gls{aic} includes year, month, port, open fishery depths, a flag for longleader trips, and the binned bag limit variable (@tbl-orbs_mod_select). Diagnostics were acceptable (@fig-orbsqq). The index of abundance is shown in @fig-orbsindex. It was not used in the base model due to the availability of a fishery-independent hook and line survey that captures a similar segment of the population. While every attempt was made to standardize the index, it can be difficult to control for all management changes that impact CPUE in fishery-dependent indices.

## Fishery-independent data

The model includes four sources of fishery-independent data: the \gls{s-wcgbt}, the \gls{s-tri}, a combined Oregon-Washington hook and line survey, and an index from standard monitoring units for the recruitment of fishes (SMURFs) in Oregon.

### \acrlong{s-wcgbt}

The \gls{s-wcgbt} is based on a random-grid design covering the coastal waters from a depth of 55-1,280 m [@bradburn_2003_2011]. This design generally uses four industry-chartered vessels per year assigned to a roughly equal number of randomly selected grid cells and divided into two 'passes' of the coast. Two vessels fish from north to south during each pass between late May to early October. This design therefore incorporates both vessel-to-vessel differences in catchability, as well as variance associated with selecting a relatively small number (approximately 700) of possible cells from a very large set of possible cells spread from the Mexican to Canadian borders.

<!-- numerical values calculated in Rscripts\process_survey_comps.R -->

Yellowtail catches in the \gls{s-wcgbt} are highest in the northern part of the coast (north of $46^{\circ}$), with some of the largest hauls close to the U.S.--Canada border (@fig-wcgbts-map). Yellowtail occur in 13% of the hauls north of $40^{\circ}10'$ and 27% of the hauls north of $46^{\circ}$. Within the 100--200 m depth range north of $46^{\circ}$, they occur in 55% of the hauls. Yellowtail are rarely found deeper than 250 m.

Geostatistical models of biomass density were fit to survey data from the \gls{s-wcgbt} using \gls{tmb} [@kristensen_tmb:_2016] via the R package \gls{sdmtmb} [@Anderson:2022:SRP] as configured within the {indexwc} R package [@johnson_indexwc_2025]. Code to reproduce the analysis is available [online](https://github.com/pfmc-assessments/indexwc). These models can account for latent spatial factors with a constant spatial Gaussian random field and spatiotemporal deviations to evolve as a random walk Guassian random field [@thorson_geostatistical_2015]. Tweedie, delta-binomial, delta-gamma, and mixture distributions, which allow for extreme catch events, were investigated. Results are only shown for the distribution that led to the best model diagnostics, e.g., similar distributions of theoretical normal quantiles and model quantiles, high precision, lack of extreme predictions that are incompatible with yellowtail life history, and low \gls{aic}. Estimates of biomass from this best model were predicted using a grid based on available survey locations.

The index was estimated for the area north of $40^{\circ}10'$ but data from south of that point were included in the analysis to better inform densities near that boundary. The annual proportion north and south of that point (Cape Mendocino) was estimated to offset the influence of changes in abundance of the southern stock from the estimates for the north.

The data were truncated to depths less than 425 m prior to modeling given that there were zero positive encounters in depths deeper than 425 m. The prediction grid was also truncated to only include available survey locations in depths between 55--425 m to limit extrapolating beyond the data and edge effects.

The final model used a delta model with a lognormal distribution for the catch-rate component. A logit-link was used for encounter probability and a log-link for positive catch rates. The response variable was catch (mt) with an offset of area (km^2^) to account for differences in effort. Fixed effects were estimated for each year. Annual proportion north and south of Cape Mendocino and pass were also included. Vessel-year effects, which were historically used for index standardization of this survey, were not included because the estimated variance for the random effect was close to zero. Vessel-year effects in \gls{s-wcgbt} index standardization were more prominent when models did not include spatial effects and instead vessel-year terms accounted for the random selection of commercial vessels used during sampling [@helser_generalized_2004; @thorson_accounting_2014].

Spatial and spatiotemporal variation was included in the encounter probability but not the positive catch rate model. Spatial variation was approximated using 400 knots, where more knots led to non-estimable standard errors because the positive encounters are too sparse to support the dense spatiotemporal structure.

The index is relatively flat except for 2014-2019 where there is a sharp increase in estimated biomass (@fig-indices).

### \acrlong{s-tri}

The \gls{s-tri} was first conducted by the \gls{afsc} in 1977, and the survey continued until 2004 [@weinberg_2001_2002]. Its basic design was a series of equally-spaced east-to-west transects across the continental shelf from which searches for tows in a specific depth range were initiated. The survey design changed slightly over time. In general, all of the surveys were conducted in the mid summer through early fall. The 1977 survey was conducted from early July through late September. The surveys from 1980 through 1989 were conducted from mid-July to late September. The 1992 survey was conducted from mid-July through early October. The 1995 survey was conducted from early June through late August. The 1998 survey was conducted from early June through early August. Finally, the 2001 and 2004 surveys were conducted from May to July. While the southern edge of the survey varied, the full latitudinal range of this assessment ($40^{\circ}10'$ N. Lat. to the Canadian border) was consistently surveyed.

Due to haul performance issues and truncated sampling with respect to depth, the data from 1977 were omitted. The surveys from 1980 through 1992 covered a depth range of 55-366 m. From 1995 through 2004, the surveys covered the depth range 55-500 m. In 2004, the final year of the \gls{s-tri} series, the \gls{nwfsc} \gls{fram} conducted the survey following similar protocols to earlier years.

The data processessing and index standardization followed a similar procedure to the \gls{s-wcgbt}, including the depth truncation, the distributional assumptions, and the number of knots. No pass covariate was included due to differences in survey design.

Because yellowtail are rarely found deeper than 366 m and are not known to undertake seasonal migrations, we included the \gls{s-tri} as a single time series following the assumption used in the 2017 assessment (@fig-indices).

### Combined Oregon-Washington Hook and Line Survey

The Marine Reserves program at \gls{odfw} and the \gls{wdfw} Coastal Marine Fish Science Unit execute standardized hook and line (or “rod and reel”) surveys that collect drift-level catch and biological data in rocky reef habitats on Washington’s nearshore waters and at four marine reserve sites that span Oregon’s coastline. Both are loosely modeled after the California marine reserves survey. The WDFW rod and reel survey was assessed in a methodology review with the \gls{pfmc} \gls{ssc} [@pfmc_gfsc_2022; @pfmc_ssc_2022], and both the ODFW and WDFW hook and line surveys have separately been used in previous assessments, including most recently the 2023 black rockfish assessments for Washington [@Cope2023wa] and Oregon [@Cope2023or]. Given the similarities in the survey protocols, these surveys were combined to produce a single index that spans the northern yellowtail rockfish stock assessment area.

The WDFW survey includes fixed standardized stations within three regional marine catch areas (i.e., MCA 2, MCA 3, and MCA 4) sampled with three replicate 8-minute drifts at each station. Details about the sample frame, site selection, and survey methodology of the WDFW survey can be found in the Groundfish Subcommittee of the \gls{ssc} Visual-Hydroacoustic Survey Methodology Review and Hook-and-Line Survey Workshop [@pfmc_gfsc_2022]. The ODFW survey includes both marine reserves and nearby comparison areas. Comparison areas are pre-selected areas with similar bathymetry and habitat characteristics as the reserve areas, but are open to fishing. Each reserve has at least one comparison area, but several have more than one. The index modeling procedure considered treatment (inside vs. outside a reserve) as a covariate. A 500-meter square grid overlaid on the area defines the ODFW sampling units or cells. Cells are randomly selected within a marine reserve or comparison area for each sampling event. The cells are considered analogous to stations in the WDFW survey. Unlike the WDFW survey, three replicate 15-minute drifts are executed in each cell. Data are aggregated to the cell-day level for ODFW data and to the station level for the WDFW data, and subsequently counts of fish per cell/station-day are used as the catch metric for CPUE. Sampling occurs in the spring and late summer/fall seasons for both surveys, but given the focus of the WDFW survey on semi-pelagic rockfish species in the spring, both data sets were subset to spring months only (March – June). This also alleviated differences in gear types between the two surveys. Throughout the history of these surveys, different gear types have been explored. Generally, the gear types mirror recreational fishing gear. Gears from each survey were categorized in several ways to evaluate as a potential covariate in the index development. Primary gear types include diamond jigs, shrimp flies, mooching jigs and other jig or combination configurations with various sizes of attached weights. There were no significant differences in the length distributions of the yellowtail rockfish encountered between the two surveys, despite the minor differences in gear (@fig-hllength). Finally, a covariate for ODFW data was created to evaluate regional spatial differences on a scale similar to the marine catch area-level in the WDFW survey. The two northern reserve areas (Cape Falcon and Cascade Head; “S5”) were combined into a single region, with Cape Perpetua (S6) and Redfish Rocks (S7) as separate Oregon regions. Each marine catch area in Washington was considered a single region (N2 – 4). Years with limited observations were removed (2009 and 2020). The final dataset contained 1,972 observations (@tbl-hl_percent_pos).

Index standardization used \gls{sdmtmb} with a negative binomial model to fit the yellowtail catch in numbers, applying a log effort offset for angler hours. Covariates evaluated include year, month, region, treatment (reserve or comparison area), a binned average drift depth, and multiple different gear categorizations. These included two different categorizations (n = 5 or n = 3) and a binomial covariate based on whether or not shrimp flies were used. None of these gear covariates were ultimately included. Some variations were not found to be significant factors based on \gls{aic} model selection, and others had strata-specific sample sizes that were too limited for models to converge. Marine reserve treatment was also not found to be a significant factor influencing CPUE in model selection, and was similarly excluded.

Two full model series were considered: one including all potential covariates with a regional covariate, and one with a survey (or state) covariate substituted for region. The best fit model according to AIC included year, region, drift depth (binned), and month. However, the Q-Q plot for this model was not ideal, so a second model series with survey was developed. In this second series, the best fit model according to AIC included year, survey, drift depth (binned), and month (@tbl-hl_mod_slx). Acceptable diagnostics were achieved when this model was fitted via MLE using the \gls{sdmtmb} R package (Version 0.6.0) @fig-hlqq. The final index of abundance is shown in @fig-indices.

### SMURF YOY Index

ODFW and Oregon State University (OSU) have collaborated on young-of-the-year (YOY) fish and environmental monitoring in and around Oregon Marine Reserves using standard monitoring units for the recruitment of fishes (SMRUF) devices. SMURFs are standardized sampling units that collect newly-settled juvenile fishes. Data were provided for two regions on the Oregon coast near the Otter Rock Marine Reserve (central) and the Redfish Rocks Marine Reserve (southern). Both regions have a site inside of the reserve and a comparison site outside of the reserve, and have sampled from 2011 to the present. These are monitored regularly (approximately every 2 weeks) during the settlement season (April - September) and YOY are collected for genetic identification and measured. Settlement rate of YOY yellowtail rockfish was provided by OSU for each site within each region. Daily mean temperature data for three depth strata (1m, 7.5m, and 15m) for each site within each region was provided by the ODFW Marine Reserve Ecological Monitoring team.

Local temperature likely impacts settlement rates. Oceanographic sampling by the ODFW Marine Reserve Ecological Monitoring team has not been done simultaneously in both reserves at each mooring site at all depths due to a lack of equipment. However, for time periods when there was matched data, temperature was highly correlated across depths (Pearson’s correlation coefficient \> 0.90) and between sites within each region (Pearson’s correlation coefficients \>0.98). In order to calculate an index of daily water column temperature that was continuous enough to be combined with settlement rate data, temperature data was standardized within year and depth. Standardizing within year means that the temperature is measuring *intra*-annual temperature variability that could impact catchability on a given collection date, and not *inter*-annual temperature variability that could impact YOY survival. For periods with multiple observations, the mean was taken in order to generate a single continuous temperature time series. Mean SMURF deployment lasted 15.5 days. In order to summarize temperature in an ecologically meaningful way relative to the SMURF sampling design, a 16-day rolling mean of temperature and cumulative degree days over 16-day periods were calculated. These data were matched with settlement rate data such that the mean temperature or the cumulative degree days during the 16-day period that the SMURF was deployed was used.

Covariates that were evaluated included year, month, region (Redfish Rocks or Otter Rock), temperature, and treatment (within marine reserve or nearby comparison site). Preliminary model runs indicated a consistent lack of convergence. Additional filters were applied including limiting the data to 2014 - 2024 and to the peak months of settlement for yellowtail (May - July). Temperature covariates explored were all binned into quantiles, depending on the range of the specific tempature covariate. Month was not included in models that included temperature, as both covariates were used to describe seasonal variation in settlement rate. Marine reserve treatment was not a significant covariate in this model, which was expected; the presence of a reserve would not be anticipated to impact juvenile settlement rates. Models were fit to the settlement rate data (YOY fish per day) using the \gls{sdmtmb} R package (Version 0.6.0) [@Anderson_2024_SRP]. Both negative binomial and tweedie distributions were evaluated. The model that was selected was based on fit (@tbl-smurf_mod_select) and expert opinion from OSU and ODFW staff. The final model contained year, region, and temperature summarized as cumulative degree days 16-days prior to SMURF recovery using a negative binomial distribution. Acceptable model convergence and other diagnostic criteria for the final index were achieved (@fig-smurfqq). The index of YOY abundance are shown in figures [-@fig-indices] and [-@fig-YOY].

### Rockfish Recruitment and Ecosystem Assessment Survey (RREAS)

The Fishery Ecology Division of the Southwest Fishery Science Center has conducted a standardized pelagic juvenile trawl survey (the Rockfish Recruitment and Ecosystem Assessment Survey, RREAS) during May-June every year since 1983 [@Ralston2013interannual; @Sakuma2016; @Field2021]. A primary purpose of the survey is to estimate the abundance of pelagic juvenile rockfishes (*Sebastes spp.*) and to develop indices of year-class strength for use in groundfish stock assessments on the U. S. West Coast. This is possible because the survey samples young-of-the-year rockfish when they are \~100 days old, an ontogenetic stage that occurs after year-class strength is thought to establish, but well before cohorts recruit to commercial and recreational fisheries. This survey has encountered tremendous interannual variability in the abundance of the species that are routinely indexed, as well as high apparent synchrony in abundance among the ten most frequently encountered species [@Ralston2013interannual; @schroeder2019source]. Past assessments have used data from this survey to provide indices of year-class strength (as relative age-0 abundance), including assessments for canary rockfish [@Langseth2023], blue/deacon rockfish [@Dick2017] widow rockfish [@Adams2019], Bocaccio [@He2015], shortbelly rockfish [@Field2007] and Chilipepper Rockfish [@Field2015].

Historically, the survey was conducted between $30^\circ 30'$ and $38^\circ 20'$ N latitude (the ‘core area’ from approximately Carmel to just north of Point Reyes, CA), but starting in 2004 the spatial coverage expanded to cover from the U.S./Mexico border to Cape Mendocino. Additionally, since 2001, data are available from comparable surveys conducted by the Pacific Whiting Conservation Cooperative (2001-2009) and the Northwest Fisheries Science Center “Pre-recruit” survey (2011-2022) for waters off of Oregon and Washington [@Field2021]. As the core area index seems to have failed to capture the magnitude of the 1999 year class for most stocks, the recommendations from the juvenile rockfish survey workshop held in 2005 were to use only the coastwide data (since 2001) for juvenile indices rather than the longer-term ‘core area’ indices.

We considered data from the RREAS survey for northern yellowtail from 2001 to 2024, the period for which we have coastwide coverage. On account of the COVID-19 pandemic, sampling in 2020 was very limited and restricted to the historical core area. Catch per tow was adjusted to a common age of 100 days to account for interannual differences in age structure [@Ralston2013interannual], as has been done for prior assessment indices using this dataset.

Since catch (and sampling) varied over space and time, we modeled catch using a spatial GLM with the package \gls{sdmtmb} [@Anderson_2024_SRP]. The 100-day standardized catch-per-tow was modeled as a function of fixed year effects along with Julian date (GAM smoother with k=4) to account for seasonality, a spatial random field, and independent identically distributed spatiotemporal random fields. We fit the model using 3 different error structures: tweedie, delta-lognormal, and delta-gamma. Dharma quantile residuals suggested that tweedie distribution was the best, so this is the model we proceeded with. The tweedie model also best reproduced the observed proportion of zeros in the data based on simulations from the fitted model. The Julian date effect increased linearly through the sampling season, which may indicate the peak of the distribution was not sampled.

We explored a coastwide index of abundance from RREAS data. An index was developed with only data north of $40^\circ 10'$, but was too sparse to provide a meaningful time series. Ultimately, the coastwide index was not included in the base model, but a sensitivity to its inclusion is described in @sec-sensitivities. The use of a coastwide index for an assessment of a stock north of Cape Mendocino was carefully considered. In addition to the sparsity of the northern index, yellowtail appear to migrate north throughout their lives (@fig-biology c). Yellowtail are densest in RREAS in Central California, in small fish in the \gls{s-wcgbt} in Oregon, and in total biomass in the \gls{s-wcgbt} in Washington. However, given the genetic separation at Cape Mendocino, it is unclear how to determine which coastwide RREAS samples are most predictive of recruitment of the northern stock. The coastwide RREAS index was ultimately not included in the base model because it seemed uncorrelated with recruitment for year-classes that are well-informed by composition data. The survey missed major recruitment events, and saw high densities of yellowtail in years with unremarkable recruitment. Yellowtail observations have been well above the long-term average in RREAS since 2021, so inclusion of the index would have major impacts on forecasts of biomass, but given the historical performance of the survey for northern yellowtail rockfish recruitment, its reliability was considered too uncertain for inclusion in the base model, particularly considering the availability other data sources.

The juvenile rockfish index (not species-specific) from RREAS for the northern California Current Ecosystem [@Gasbarro2025] is in our comparison of juvenile abundance datasets (@fig-YOY), but this index was only considered for comparative purposes and was not considered for the assessment model or sensitivity runs based on recommendations from the juvenile rockfish survey workshop.

### Biological data

Length and age data were available from the \gls{s-wcgbt} and \gls{s-tri} (@tbl-wcgbts-bio, @tbl-tri-bio, @fig-len-all-bubbles, @fig-age-all-bubbles, last two rows). There were 17,329 length observations in the \gls{s-wcgbt} data set, of which only 22 were unsexed, so the unsexed samples were excluded. There were 14,275 lengths in the \gls{s-tri}, none of which were unsexed. Composition data were processed using the {nwfscSurvey} R package, which weights samples for marginal distributions by biomass at the tow and stratum level [@Wetzel2025]. Data were separated into two strata: samples shallower and deeper than 183 m. This is consistent with the stratification for the \gls{s-wcgbt} sampling design. \Gls{s-tri} composition data are based on the same stratification scheme (though it is unrelated to the survey design). Ages from the \gls{s-wcgbt} were conditioned on length while the age data from the \gls{s-tri} were processed as marginal distributions. For the conditional age-at-length data, the number of fish within each length bin within each sex is used as the input sample size. The input sample sizes for the marginal distributions are based on the formula of @Stewart2014 as $\text{Input N}_{y} = 2.43*N_{tow}$ where the scalar was estimated for a group of 17 shelf rockfish, including yellowtail rockfish. Unsexed length compositions from the combined Oregon-Washington hook and line survey are included without any expansions, using number of fish as the input sample size. Length compositions were filtered to reflect those included in the final filtered CPUE index (n = 1,658 fish, @fig-len-all-bubbles, fourth row).

Surveys collect data in a standardized way with recorded locations that can be helpful for exploring empirical patterns in species biology that may inform modeling practices. There is a slight pattern where length-at-age in the \gls{s-wcgbt} decreased around 2014 (@fig-biology b), coincident with the increase in CPUE (@fig-indices). Length-at-age appears fairly consistent along the coast within the model area (@fig-biology a), though average age increases north along the coast (@fig-biology c).

## Ageing error {#sec-ageing}

<!-- see Rscripts\process_double_reads.R for the data processing and analysis -->

The age composition data was based on age estimates provided by two labs, \gls{wdfw} and the Cooperative Ageing Project (CAP) under the Pacific States Marine Fisheries Commission. There were a total of 6,339 otoliths with multiple age readings, 4,402 aged by WDFW readers only, 1,716 by CAP readers only, and 221 aged by readers from both labs.

A series of models estimating ageing error were explored to estimate variability in age estimates as a function of age and to test for differences between labs and among readers. This analysis was conducted using the {AgeingError} software package [@punt_ageingerror_2025] which is based on @punt_quantifying_2008. The estimated differences between the two labs was negligible; the labs differed by an average of 0.6%, or less than 0.25 years for a 40-year-old fish. Similarly, the estimated CV of the age reads was similar between labs: 0.0615 for the WDFW lab and 0.0595 for the CAP lab. The differences among readers within labs were likewise small. Therefore, the most parsimonous model was chosen, which was to treat all readers equally and estimate a single CV parameter relating ageing uncertainty to age. The estimated CV was 0.0606 which corresponds to a standard deviation of 1.2 years for a 20-year old fish and 2.4 years at age 40. This estimate is similar to the results of the ageing uncertainty estimation in the 2017 assessment and indicates that ageing is more precise than for many other west coast groundfish. The relatively precise ageing is corraborated by one of the age reader's comments that yellowtail rockfish are extremely easy to age (B. Kamikawa, pers. comm.).

## Biological Parameters

### Natural Mortality

The model freely estimates natural mortality. However, a lognormal prior based on maximum age is applied [@hamel2022development]. The maximum age used for the prior is 43 years, which is the 99.9th percentile of the 161,828 ages available in \gls{pacfin}. Because so much age data is available, use of the absolute maximum age observed is subject to influence from outliers. There were 131 samples in \gls{pacfin} between ages 43 and 60 with roughly exponentially decreasing frequency-at-age, and one extreme outlier aged at 77 years. Half of these 132 oldest ages were from samples prior to 1984. The maximum age of 43 is associated with a median natural mortality rate of 0.126 yr$^{-1}$.

An unusual phenomenon in yellowtail rockfish data is an increasingly male-skewed sex ratio at older ages. This is shared with several other rockfish species, including black rockfish, which is closely related to yellowtail, and canary rockfish. All data sources for this assessment (commercial, recreational, and survey data) show this pattern; however, below age 20, the recreational fleet has a female-skewed sex ratio, while the trawl gears have a sex ratio that is more evenly balanced (@fig-biology d). Over the years, assessments for all three species have explored whether this pattern is due to differences between the sexes in selectivity, mortality, or some combination. It appears females tend to die at younger ages even in aquarium settings, supporting that the phenomenon is at least in part due to natural mortality (L. Rasmuson, ODFW, pers. comm.).

### Weight-at-length

Sex-specific weight-at-length was estimated using a log-transformed linear regression and then bias corrected to predict mean weight-at-length rather than median weight-at-length; however, the curves for the two sexes are very similar (@fig-length-weight). Initial data exploration indicated that some years tended to have consistently negative or positive residuals to this single regression equation (i.e., fish condition varies across time). A time-varying weight length relationship is explored in @sec-sensitivities. At present, time-varying biology can bias reference point calculations in the stock synthesis modeling platform (R. Methot, pers. comm.), so this was not considered a good choice for a base model. The time-invariant weight length relationship used was $W =$`r mod_in$ctl$MG_parms['Wtlen_1_Fem_GP_1', 'INIT']`$L$^`r mod_in$ctl$MG_parms['Wtlen_2_Fem_GP_1', 'INIT']`^ for females and $W =$`r mod_in$ctl$MG_parms['Wtlen_1_Mal_GP_1', 'INIT']`$L$^`r mod_in$ctl$MG_parms['Wtlen_2_Mal_GP_1', 'INIT']`^ for males.

### Maturity

We used a total of 232 individual histological samples of aged female yellowtail rockfish to estimate maturity for the assessment. These samples were all collected north of $40.167^\circ$ N. The 232 samples were collected over the period 2016—2023, though more samples were collected earlier in these years (n = 111 in 2016, 52 in 2017, 31 in 2018, 17 in 2021, 9 in 2022, 13 in 2023). Previous assessments of yellowtail estimated length-based maturity (L50 = 42.49cm in 2017 assessment); however, we switched to an age-based model for the current assessment. For many species, energy is reallocated toward maturation from growth, and as a result growth rates slow during the juvenile to adult transition period. Thus, length at 50% maturity will represent a range of ages, providing a less accurate understanding of the spawning population. We treated maturity as a binomial response, and considered a variety of models with temporal and spatial covariates, using a logit link and generalized linear mixed model framework, implemented using the R package \gls{sdmtmb} [@Anderson_2024_SRP]. Briefly, we considered models that included (1) temporal year effects (either estimated as a random walk intercept, or smooth term), (2) spatial random fields (using a mesh cutoff distance of 50km), and (3) spatially varying coefficients of age, following the model adopted by @grandin_status_2024. Models that converged were compared by examining QQ plots, AUC metrics, and AIC scores. Likely because of the uneven temporal distribution of sampling, and general sparsity, we did not find support for including temporal or spatial effects, and decided on the simpler null model (equivalent to a logistic regression). For the age-based model, we estimated an intercept of -6.70 (SE = 0.99) and slope of 0.67 (SE = 0.10), equivalent to an A50 of 10.0 years (@fig-maturity). For a more direct comparison to the previous assessment, we used these same 232 samples to fit an equivalent length-based model, which resulted in an estimated L50 = 42.5 cm, essentially identical to the value used in 2017.

### Fecundity

Fecundity is based on @dick_meta-analysis_2017 and is unchanged from the 2017 assessment. The relationship for spawning output for an individual is `r mod_in$ctl$MG_parms['Eggs_alpha_Fem_GP_1', 'INIT']`\*length^`r mod_in$ctl$MG_parms['Eggs_beta_Fem_GP_1', 'INIT']`^.

## Environmental and ecosystem data

### Oceanographic Index

Over the past several years, progress has been made in understanding how oceanographic conditions drive recruitment of groundfish species in the California Current Ecosystem across life stages for petrale sole, sablefish and Pacific hake. Recent increases in staff capacity supported by the Climate, Ecosystem, and Fisheries Initiative provided the ability to build on these previous lines of research and examine the relationship between northern yellowtail rockfish recruitment and oceanographic drivers based on model output from Global Ocean Physics Reanalysis (GLORYS) from [Copernicus Marine Environment Monitoring Service](https://marine.copernicus.eu/) (CMEMS) and Regional Ocean Modeling System (ROMS) model for the California Current Ecosystem [@neveu2016ROMS]. The results suggest that GLORYS output may allow for better model precision and near-term forecasting than ROMS. This approach builds on previous research [@tolimieri_oceanographic_2018; @haltuch_oceanographic_2020; @vestfals2023stage] and assessments [@Taylor_petrale_2023; @berger_status_2023; @grandin_status_2024] by applying similar techniques to establish oceanographic relationships and develop an oceanographic index based on a conceptual life history model for yellowtail rockfish [@Darby]. GLORYS also provides a temporally robust time series and is not susceptible to discontinuities identified in the 2023 petrale sole assessment [@Taylor_petrale_2023]. Appendix A of this report describes the most recent efforts in developing a new environmental index of northern yellowtail recruitment based on GLORYS products. The final selected oceanographic model included the date of spring transition from the Coastal Upwelling Transport Index, degree days (which represents temperature exposure) during egg fertilization and development, long-shore transport during the pelagic juvenile lifestage, and El Niño conditions during the pelagic juvenile lifestage. The oceanographic model was fit using the recruitment deviations (1994 - 2019) from the base model and used to predict log-recruitment deviations for the next five years, 2020 - 2024, using oceanographic conditions. The index is not included in the base model, but sensitivity to including the final five years (predicted log-recruitment deviations only) is explored in @sec-sensitivities.

## Data sources evaluated, but not used in the assessment model

### Washington recreational dockside catch-per-unit-effort

\Gls{wdfw} gathers data on catch and effort in the state’s coastal recreational fisheries. This dockside interview data was initially considered a fishery-dependent index of abundance in the assessment. However, a combination of different factors, including changes in management measures (e.g., bag limit changes) and the lack of finer-scale measures of effort available, warrants further consideration to address potential shifts in fishing behavior and necessitates further evaluation of whether the data could provide a reliable signal on abundance to be used in future assessments.

### Olympic Coast National Marine Sanctuary Dive Survey

Data from young-of-the-year dive surveys conducted between 2015 and 2024 from waters within the Olympic Coast National Marine Sanctuary (OCNMS) were provided by Nick Tolimieri and Ole Shelton (NWFSC). These data were first considered for use in stocks assessment in @Cope2023wa. The survey uses SCUBA and belt transects to estimate rockfish abundance, where yellowtail are identified as a black-yellowtail (BYT) complex based on coarsely binned (2-5cm) length compositions. Detailed description of survey methods and aims are found in @Tolimieri2023. The YOY survey is interpreted as an index of age-0 abundance, though admittedly a rough one as it combines yellowtail rockfish and black rockfish because they are visually indistinguishable at the surveyed size and age. For the purposes of this assessment, these data are compared to other indices of YOY and recruitment trends to consider shared patterns in variability and whether the trends in these data are consistent with the trends in the overall assessment and across other early life history indices (@fig-YOY)

### Juvenile abundance index considerations

One of the challenges of stock assessment for yellowtail rockfish is that they are not well represented in survey data until they are 6-7 years old, which makes forecasts used for setting catch limits subject to substantial uncertainty due to the uknown strength of many year classes that contribute to spawning output. In order to address this challenge we considered five indices of age-0 abundance or recruitment based on YOY surveys and oceanographic information (@fig-YOY). To prioritize which dataset would be most informative, we considered the benefits and drawbacks of the sampling design and data availability of each dataset (@tbl-consider). Multiple indices showed some degree of synchrony. The northern YOY rockfish index, oceanographic index, and SMURF index all captured an increase in abundance from 2019 - 2021, followed by low abundance in 2022, and an increase in abundance in 2023 although the magnitude of abundance in 2023 varied across data sources.

We prioritized the SMURF index in the base model based on an assessment of the benefits and drawbacks of each potential dataset (@tbl-consider) and considered the oceanographic index and yellowtail RREAS index as sensitivity runs (@sec-sensitivities). Both the OCNMS nearshore survey and the northern YOY rockfish index are estimates of abundance that are not specific to yellowtail, and we felt the three age-0/recruitment indices we did consider were higher quality given their specificity (@tbl-consider). The RREAS coastwide index did not seem to capture the low juvenile abundance identified across indices in 2022. In addition it estimated an increase in abundance between 2023 and 2024 where the oceanographic and SMURF indices estimated a decline (@fig-YOY). Similarly, the oceanographic index was higher than other indices in 2018 (@fig-oc_model and @fig-YOY).
