# Assessment Model

## History of modeling approaches

<!-- Very brief text here for (IT will do) -->

@fig-historical shows the timeseries of age 4+ biomass for yellowtail rockfish across past assessments. Early studies of yellowtail rockfish on the U.S. West Coast north of $40^\circ 10^\prime$ N. latitude (Cape Mendocino, northern California) began in the 1980s with observational surveys. Statistical assessments of yellowtail rockfish were conducted in 1982 [@Tagart1982], 1988 [@Tagart1988], 1996 [@Tagart1997], and 1997 [@Tagart1997] to determine harvest specifications for the stock. These early assessments employed a variety of statistical methods. For example, the 1997 assessment used cohort analysis and dynamic pool modeling. 

The yellowtail rockfish assessment in 2000 [@Tagart2000] was the first that estimated stock status, with an estimated depletion of 60.5% at the start of 2000. Lai et al. [@Lai2003] updated the 2000 assessment and estimated that stock depletion was 46% at the start of 2003. A second assessment update was prepared in 2005 [@Wallace2005] with an estimated depletion of 55% at the start of 2005. The 2000 assessment and updates were age-structured assessments conducted using AD Model Builder as the software platform for nonlinear optimization [@Fournier2012].

A data-moderate assessment of yellowtail rockfish north of $40^\circ 10^\prime$ N. latitude was conducted in 2013 [@Cope2013]. The data-moderate approach included only catch and indices of abundance with no age or length composition data included.

The most recent assessment was conducted in 2017 [@stephens_status_2017] which returned to the benchmark approach and included age and length composition data and modeled discards through a parametric retention function fit to discard length compositions and discard rates. In the same year the first assessment for the stock of yellowtail rockfish south of $40^\circ 10^\prime$ was attempted, but the data were not adequate to provide reliable estimates and the assessment was withdrawn having been found to be too uncertain for management [@stephens_status_2017].

## Response to most recent STAR panel and SSC recommendations

-   Additional investigations that better quantify the male-skewed sex ratio at older ages, and evaluate potential mechanisms for the observed discontinuities, should be pursued.
    -   We have run a number of sensitivities involving different parameterizations of natural mortality and selectivity and included data plots that further explore this dynamic, as well.
-   The draft northern yellowtail assessment models included indices of relative abundance based on fishery-dependent time series, including a trawl logbook CPUE index and an index of abundance based on yellowtail bycatch in the at-sea Pacific whiting fishery. During the STAR panel, these were removed from the final base model. However, as the indices were influential with respect to model results, greater exploration of the potential for these data to inform a relative abundance index, particularly for the trawl logbook cpue data, would benefit future assessment efforts.
    -   As the 2017 review found, historical logbook data is extremely difficult to standardize in a reliable way. However, we have explored data from the current \gls{wcgop} program as an alternative fishery-dependent index from the trawl sector, covering a later subset of years.
-   Consideration of alternative survey methods (e.g, acoustic surveys, midwater trawl surveys) and/or the means to account for changes in catchability that may be associated with environmental factors, could improve the ability of survey indices to track stock abundance.
    -   We have included a new hook and line index in the assessment. However, this remains a key research priority, made even more clear by the inability of the model to fit the peak and rapid decline in the trawl survey index since the 2017 assessment. This issue cannot be addressed via assessment modeling, and needs targeted research between assessment cycles.
-   Combined US/Canadian transboundary assessment.
    -   This remains an important research priority.
-   Common documentation of data streams and sources to support fishery independent and fishery dependent indices and compositional data could reduce the burden on assessment analysts to provide details about each data source, and allow reviewers a robust source of information on the most important, common data sources for any given stock assessment cycle.
    -   The stock assessment program at \gls{nwfsc} has made great strides in improving data processing since 2017 through a number of standardized R packages for commercial and survey data. This assessment gratefully utilized these tools.

```{=html}
<!-- Response to the most recent previous STAR panel and SSC recommendations for remedying deficiencies in the most recent previous full assessment. This is not required for an update assessment.  
Is this required if there are no "deficiencies"? -->
```

## Model Structure and Assumptions

### Model Changes from the Last Assessment

<!-- Description of new modeling approaches and changes made from the last assessment, with rationale. This should include bridging analyses that highlight the data and model changes that were most influential with respect to changes between the assessment being reviewed and the most recent adopted assessment.  -->

The following bullets list major changes from the 2017 benchmark assessment [@stephens_status_2017]:

-   Reanalyzed and extended all relevant data sources through 2024.

-   Early data exploration indicated that commercial fishery composition data was likely entered as "raw" in 2017, which is not the default approach recommended by the [PFMC groundfish assessment accepted practices document](https://www.pcouncil.org/documents/2025/03/accepted-practices-guidelines-for-groundfish-stock-assessments-accepted-practices-guidelines-for-groundfish-stock-assessments-in-2025-and-2026-march-2025.pdf/). That is, each individual sample was equally weighted, rather than weighting samples based on catch amounts at the trip and state level. This assessment uses the \gls{nwfsc} R package {pacfintools} [@wetzel_pacfintools_2025] to summarize age and length composition data from the commercial fishery.

-   Added combined hook and line index as a CPUE index in units of number of fish.

-   Added SMURF index as an index of recruitment.

-   Esimated commercial discards from the \gls{gemm} report were added to landings rather than modeled separately through a parametric retention.

-   Updated ageing error as described in @sec-ageing.

-   Used a single recreational fleet instead of separating Washington from Oregon and California north of $40^{\circ} 10'$. Most Washington recreational catch data is now available in biomass on \gls{recfin}. This facilitated combining recreational catches across all three states into a single model fleet with catch supplied in biomass. Different catch reporting units was the main reason listed for separating the recreational fleets in 2017.

-   Added foreign trawl catches from 1966-1976 to the commercial fleet.

-   Recreational fishery selectivity is modeled as sex-specific, with different descending limbs for males and females and males having an overall lower likelihood of being selected. This greatly improved fits to recreational length and age composition data.

-   Added additional selectivity blocks for 1) recreational selectivity beginning in `r mod_in$ctl$Block_Design[[1]][3]`, when trips in both Oregon (longleader gear) and Washington (avoiding black rockfish) were reported to get deeper and 2) the at-sea hake fishery beginning in `r mod_in$ctl$Block_Design[[2]][1]`. The at-sea hake fishery is highly mobile and moves around to wherever hake are densest and bycatch species can be avoided. It has been occurring farther south in recent years.

-   The fishery-dependent indices included as sensitivities in 2017 were not reproduced or extended.

-   The maximum age in the data bins increased from 25 to 30 to better match observed data.

### Modeling Platform and Structure

The stock assessment is conducted in Stock Synthesis version 3.30.23.1 compiled December 5, 2024 (available [online](https://github.com/nmfs-ost/ss3-source-code/releases/tag/v3.30.23.1)). The model is sex-specific and includes three fishery fleets (commercial, at-sea hake, recreational) and 4 surveys (an Oregon-Washington combined hook and line survey, the \gls{s-tri}, the \gls{s-wcgbt}, and the SMURF index). There is a single model area from $40^{\circ} 10'$ N to the Canadian border. The model begins in `r mod_in$dat$styr`, which is the earliest year of the commercial catch reconstruction. The population was assumed to be unfished and at an equilibrium age structure at this point. The first length composition data included in the model is in `r min(mod_in$dat$lencomp$year)`. Early recruitment deviations are estimated from `r mod_in$ctl$recdev_early_start` to `r mod_in$ctl$MainRdevYrFirst - 1` to better match the age structure at the start of the composition data. The model configuration is summarized in @tbl-model-config.

<!-- Assessment program and its version used for the assessment (i.e., date executable program file was compiled), description of model structure, definitions of fleets and areas. Description of how the first year that is included in the model was selected and how the population state at the time is defined (e.g., B0, stable age structure). -->

### Model Parameters{#sec-pars}

The base model had `r sum(mod_out$parameters$Phase > 0)` estimated parameters (tallied by type in @tbl-n-param).
Due to the richness of age composition data, most life history parameters were estimable. Natural mortality and growth are both estimated separately for males and females with shared parameters for length at age 2 and CV of length-at-age for young fish. Separate values for small fish were not estimable, nor was the four-parameter Richards growth curve. Male values were estimated as an offset of female values. A prior was placed on female natural mortality, but the data overwhelmed it (@fig-param-dist, @fig-m-profile and discussed in @sec-profiles). Unfished recruitment is estimated. Steepness of the stock-recruit relationship was kept fixed at 0.718, matching the 2017 assessment. This is a more precise value than the 0.72 specified in the PFMC Terms of Reference for rockfish assessments and Accepted Practices Guidelines, but explorations of the difference showed negligible impact of this difference (e.g. 0.001 units of relative spawning output). When estimated, steepness goes to 1.0. The standard deviation of log-recruitment deviations is `r mod_in$ctl$SR_parms['SR_sigmaR', 'INIT']`, similar to the value used in 2017. Reevaluating the tuning of this parameter indicated no changes were necessary [@methot_adjusting_2011]. Recruitment deviations during the "main" period (from `r mod_in$ctl$MainRdevYrFirst` to `r mod_in$ctl$MainRdevYrLast`) were forced to sum to zero. Relaxing this assumption led to no visible changes in the model, and the constraint allows for clearer interpretation of management reference points.

Length, age, and age-at-length composition data weights were tuned using the Francis method [@francis_data_2011, @tbl-compweight]. All selectivity was assumed to be length-based and used a double-normal functional form. We explored age-based selectivity, but due to sexual dimorphism, fitting the composition data well would have required a more complex formulation with additional estimated parameters. Selectivity was estimated to be sex-specific and dome-shaped for the recreational fleet with three base parameters (ascending and descending limbs and length at peak selectivity) and two sex-specific parameters (descending limb and scaling factor for males) being estimated. Selectivity for the hook and line survey was also dome-shaped, but male parameters were not well-estimated, likely because the the length composition data is not sex-specific, so selectivity was shared for the two sexes. All other fleets had a single shared asymptotic selectivity for both sexes. Early explorations into dome-shaped selectivity for fleets using predominantly trawl gear indicated that the descending limbs were estimated at the far right side of the length distribution such that few fish were actually observed or expected to exist in the range of the descending limbs. Sex-specific selectivity for fleets using trawl gear did not visibly improve fits to composition data, so were not considered for the base model, though a sensitivity is shown. The length at peak selectivity consistently hit the upper bound for the triennial and at-sea hake fleets, so was fixed at 55 cm, near the maximum data length bin.

Selectivity was constant across time for all but the recreational and at-sea hake fleets. Recreational selectivity is estimated across three time periods: model start to `r mod_in$ctl$Block_Design[[1]][1]-1`, `r mod_in$ctl$Block_Design[[1]][1]` to `r mod_in$ctl$Block_Design[[1]][2]` when depth restrictions were in place to prevent catch of overfished rockfish, and `r mod_in$ctl$Block_Design[[1]][3]` to `r mod_in$ctl$Block_Design[[1]][4]` to account for the growing longleader fleet in Oregon and avoidance of black rockfish in Washington, both of which led to recreational trips occurring farther offshore and catching larger fish. The sex-specific parameters were assumed to be constant. The at-sea hake fleet has estimates of selectivity across two time periods: the start to `r mod_in$ctl$Block_Design[[2]][1]-1` and `r mod_in$ctl$Block_Design[[2]][1]` to `r mod_in$ctl$Block_Design[[2]][2]`. While no particular management change warranted this block, the at-sea hake fleet is highly mobile from year to year and does not target yellowtail, so changes in selectivity across time are likely. Length compositions became smaller than expected around the time of the block, particularly for females, a misfit that was not seen across other fleets. The hake fishery has occurred farther south in recent years, where yellowtail do tend to be younger, and therefore smaller (@fig-biology c). Due to the smaller sized fish in recent years, the length at peak selectivity *was* estimable for the later period for the at-sea hake fleet.

<!-- Model parameters: estimated and fixed parameters, constraints on parameters, selectivity assumptions, natural mortality, treatment of age reading bias and/or imprecision, and other fixed parameters, description of stock-recruitment constraints or components, critical assumptions, and consequences of assumption failures.  -->

### Key Assumptions and Structural Choices

Modeling choices were made to seek balance between model realism and parsimony. See @sec-pars for further details on these choices and alternatives considered.

<!-- Evidence of search for balance between model realism and parsimony. Key model assumptions and structural choices (e.g., asymptotic vs. domed selectivities, constant vs. time-varying selectivities). Summary of alternate model configurations that were examined but rejected. This is not required for an update assessment. -->

### Bridging analysis

Reanalyzing catch data led to an increase in population scale due to the addition of a large amount of foreign landings in the 1960s and 1970s (Figures [-@fig-bridge1-ssb] and [-@fig-bridge1-depl]). Reanalyzing the triennial and WCGBTS indices led to a small increase in scale and a decrease in the maximum spawning output around 2012. Updating the biology (length-weight and maturity relationships) led to an increase in scale, mainly due to the change to age-based maturity. Changing the treatment of discards led to minimal changes. The relative spawning output in 2017 is similar across all models incorporating these changes.

Reanalyzing composition data led to more significant changes, particularly with the reanalysis  of age data (Figures [-@fig-bridge2-ssb] and [-@fig-bridge2-depl]). Deeper investigation indicated that treatment of commercial composition data in 2017 differed from standard practices for a data-rich stock such as yellowtail; it did not weight samples by catch at the trip or state level, and instead appears to have entered data "raw." The current model *does* weight samples using the NWFSC R package \{pacfintools\}. Expanding commercial age data in particular leads to a lower population scale and lower terminal relative spawning output compared to the 2017 base model and the model from the first set of bridging steps. Finally, extending all data sources to 2024 leads to a different perception of the population peak around 2012. Rather than peaking and steeply declining, the population is relatively stable from around 2010-2015, and declines only in years since the last assessment. The additional eight years of data leads to much higher estimates of the 2006-2008 recruitment deviations, where the 2008 year class is now estimated as the largest year class on record. After reanalyzing and extending all data sources, the estimate of unfished spawning output is nearly identical to the estimate from the 2017 model. However, spawning output in 2017 is estimated slightly lower, leading to a slightly lower relative spawning output, but well within the estimated uncertainty from the 2017 model. Spawning output in the 1980s and 1990s in the model with extended data is estimated to be near the lower limit of the confidence interval from the 2017 model.

The modeling update that led to the largest change in the estimated population trajectory was changing the recreational blocking, which included the addition of a new block in 2017 and led to a decrease in the population beginning around 2012 (Figures [-@fig-bridge3-ssb] and [-@fig-bridge3-depl]). Rather than attribute the additional large fish in the recreational composition data to changes in the population, the model now attributes them to selectivity changes. The updated block improved the likelihood by 20 units and estimated only two additional parameters. (The ascending limb parameter is assumed to be shared across time.) Sex-specific recreational selectivity substantially improved fits to both age and length data from the recreational fleet, but did not lead to major changes in model outputs. (Improvements were so great the model needed to be retuned to upweight recreational data, but as a result likelihoods are not comparable.) The block in hake selectivity, combined hook and line index, SMURF index, and various other updates (updating the natural mortality prior and aging error, minor corrections to input data) all had limited impacts on the estimate of the population trajectory. The terminal depletion and spawning estimates from the 2017 assessment are well within the estimated confidence intervals for 2017 in the current model, and the estimates of terminal depletion and spawning output in 2017 from the current model are well within the estimated confidence intervals in the 2017 model. The additional data and modeling changes have also narrowed the uncertainty in population scale (i.e., unfished spawning output). 
