## Base model results

### Parameter estimates

Parameters were estimated using maximum likelihood estimation and uncertainty is based on the assumption of asymptotic multivariate normality of the maximum likelihood estimate, where the variance-covariance matrix is the inverse of the hessian matrix. A list of fixed and estimated parameters in the model and asymptotic standard error estimates for estimated parameters is available in @tbl-pars.

Exploratory MCMC runs indicated that posterior distributions largely matched these asymptotic distributions, but took much longer to produce. The parameter where the posterior distribution diverged the most from the maximum likelihood was the descending slope of the recent recreational selectivity, where the MLE corresponded to a gently declining selectivity. The posterior mode matched the MLE, but a large fraction of the posterior samples were from higher values corresponding to asymptotic selectivity. 

<!-- Population numbers and biomass at age × year × sex (if sex-specific M, growth, or selectivity) (may be provided as a text, csv, or spreadsheet file). This is not required while undergoing review. Can be included in electronic appendices (SS report files), should be provided as supplementary material for assessments developed with alternative assessment platforms.  -->

Selectivity curves by length and age indicate that all trawl-based gears have fairly similar selectivities (Figures [-@fig-sel-length], [-@fig-sel-age]), whereas hook and line gears select smaller fish. Selectivity of males in the recreational fleet is lower than it is for females, consistent with the high percent females observed in that fleet until around age 20 (@fig-biology d). Time-varying selectivity for the at-sea hake and recreational fleets is in @fig-sel-tv. 

The estimates of recruitment and spawning output indicate a weak stock-recruit relationship over the observed range of spawning output (@fig-s-r). 

The estimated length-age relationship is in @fig-growth1, and the relationship between growth (estimated internally), maturity (estimated externally) and weight (estimated externally) is in @fig-growth2.

### Fits to the data

The model fits all indices reasonably well with the exception of the \gls{s-wcgbt} index which has a group of large observations (4 out of the 6 years in 2014-2019) which are not fit well (@fig-indices_fit). The challenge of fitting these points is discussed in @sec-unresolved. The \gls{s-tri} shows changes among the years 1995, 1998, 2001, and 2004 which are too large to represent reasonable population dynamics and are also not fit will by the model. The fit to the SMURF index is achieved through estimates of recruitment deviations during the period covered (2014--2024), but the penalty on deviations away from zero associated with the sigmaR parameter leads to less good fits to the low observation in 2015 and the high observations in 2021 and 2023.

Fits to length composition data are generally good (@fig-len-agg-fit). The model does estimate a more left-skewed distribution of female lengths in the commercial fleet than is observed. The hook and line survey has more fish observed at peak length and fewer samples in the right tail than expected. The WCGBTS has a more peaked distribution for males than expected by the model. Across time, fits are poorest for the commercial fleet early in the time series when data are more sparse, and from 2009 to 2015 when the average length observed was higher than the model estimate (Figures [-@fig-len-all-pearson], [-@fig-mean-len-1]). The STAT was not aware of management changes covering this period in particular that could explain this misfit. However, fits to length data in recent years are better. The length distribution for males in the WCGBTS in 2024 was more steeply peaked than the predicted value, a more extreme example of the pattern observed when aggregated across years (Figures [-@fig-len-all-pearson], [-@fig-mean-len-6]). Fits to length data across time for other fleets were generally not notable (Figures [-@fig-len-all-pearson], [-@fig-mean-len-2]--[-@fig-mean-len-5]).

Fits to marginal age data were also generally good, though somewhat noisier for the at-sea hake and triennial fleets (@fig-age-agg-fit). The male commercial age distribution is slightly more left skewed than expected, and the distribution for females is slightly more right-skewed than expected. The recreational fleet observes more females from around ages 10-20 than expected. Across time, fits to the 1997 recreational age data were quite poor, and observations were much older than expected; this was true to a lesser extent in 2014, as well (Figures [-@fig-age-all-pearson], [-@fig-mean-age-3]). The 1997 ages came from around 100 individuals, and WDFW staff could not identify any reason these samples would not be representative of the population, so they were retained in the model. Otherwise there were no particularly notable patterns (Figures [-@fig-age-all-pearson], [-@fig-mean-age-1]--[-@fig-mean-age-4]). 

Fits to conditional age-at-length data are harder to evaluate, but generally seem acceptable (Figures [-@fig-caal-page1]--[-@fig-caal-page3]). There is possibly an increase in positive residuals for older age-at-length and negative residuals for younger age-at-length in recent years that would be consistent with the observed patterns of decreasing length-at-age in the data (@fig-biology b). This appears more notable for males than females. Fits to the marginal age distributions not present in the likelihood (figure in r4ss appendix) and mean age over time (@fig-mean-age-5) showed no concerning patterns.

### Population trajectory

The estimated population trajectory indicates the population declined slowly with the initial onset of fishing, and then declined steeply with the onset of the midwater trawl fishery around 1980 and was near the minimum stock size threshold throughout the 1980s and 90s; it then increased beginning around 2000, peaked around 2012, and has been declining in recent years, but is currently estimated to be well above the management target (@tbl-ts, Figures [-@fig-sb], [-@fig-depl], [-@fig-spr], [-@fig-spr-phase], [-@fig-dyn-b0]). Recruitment is estimated to be highest in 2008 (Figures [-@fig-recruits], [-@fig-recdevs]). This strong year class (and, to a lesser extent, the 2006 and 2010 year classes) was apparent across all sources of composition data, and was also supported by increases in the combined hook and line and bottom trawl surveys as those year classes became selected. Recruitment is estimated to be low throughout the late 2010s; however, the SMURF index suggests large year classes from 2021 and 2023 may be entering the population.
