## Model Diagnostics

```{=html}
<!-- If a range of model runs is used to characterize uncertainty, it is important to provide some qualitative or quantitative information about relative probability of each. If no statements about relative probability can be made, then it is important to state that all scenarios (or all scenarios between the bounds depicted by the runs) are equally likely.  
If possible, ranges depicting uncertainty should include at least three runs: (a) one judged most probable; (b) at least one that depicts the range of uncertainty in the direction of lower current biomass levels; and (c) one that depicts the range of uncertainty in the direction of higher current biomass levels. The entire range of uncertainty should be carried through stock projections and decision table analyses.  -->
```

### Convergence

```{r}
#| label: 'jitter'
#| echo: false 
#| eval: true 
jit <- read.csv(here::here("report/diagnostics/jitter_results.csv"))
jit_good <- sum(jit$Lowest.NLL == "Best Fit")
jit_total <- nrow(jit)
```

The maximum parameter gradient was `r signif(mod_out$maximum_gradient_component, 2)` and the jitter analysis showed that `r jit_good` out of `r jit_total` model runs with jittered initial values converged to the same model estimate.

### Sensitivity Analyses{#sec-sensitivities}

We conducted a number of model runs exploring sensitivity of the model to decisions regarding data and model structure. They are briefly described below:

-   Index sensitivities
    -   Remove all indices (Triennial, WCGBTS, SMURF, combined hook and line)

    -   Remove SMURF index

    -   Add fishery-dependent WCGOP index

    -   Add oceanographic index (included as index of recruitment deviations, only include years not present in training data: 2019-2024, fix catchability at one, since only other "data" to inform estimate of catchability during the years the index is included is the prior pulling recruitment deviations to zero)

    -   Add ORBS index (no added SE)

    -   Add ORBS index (with added SE)

    -   Add RREAS index (included as index of absolute recruitment)

    -   Upweight WCGBTS index (fix SE of log of index to 0.05)
    
-   Modeling sensitivities

    -   Estimate 1) natural mortality for all males and females through age 9, and 2) natural mortality for females aged 10 and older (based on age at 50% maturity of 10 years)
    
    -   No sex selectivity for the recreational fleet
    
    -   Estimate sex selectivity for all trawl fleets (ascending limb and scale)
    
    -   Estimate shared natural mortality for males and females
    
    -   Time-varying weight-length relationship for years with WCGBTS data
    
    -   Hybrid F method (an alternative approach to internal calculations of fishing mortality which treats F as a continuous rate rather than using Pope's approximation)
    
    -   Estimate a density-dependent parameter for WCGBTS catchability
    
-   Composition data sensitivities

    -   McAllister & Ianelli data weighting
    
    -   Remove all lengths from fishery data (selectivity remains length-based and uses the growth curve estimated from survey data and age compositions from fishery fleets)
    
    -   Add unsexed commercial lengths
    
    -   This is short. Could add: unexpanded PacFIN data, only include comp data from WA. (assume OR/CA would have opposite effect, WA has advantage of ageing rec fish)

#### Indices

Model sensitivity to index data is in figures @fig-index-sens-ssb and @fig-index-sens-depl and table Z.

The ORBS index suggests a higher unfished population scale and lower terminal year depletion below the management target. Unfished recruitment is actually lower, but natural mortality is also lower, and the growth curves differ (lower L$_\infty$, higher K, more similar growth for males and females in model with ORBS index). Overall these differences result in a higher unfished spawning output, similar terminal year spawning output, and therefore lower terminal year relative spawning output. However, the input standard errors on the ORBS index are lower than for any of the fishery-independent indices, which is likely unrealistic. When the model is given the freedom to downweight the index by estimating an additional standard error, the model trajectory is very similar to the base model.

Removing all indices results in a higher unfished recruitment, higher natural mortality, and similar unfished spawning output compared to the base model. (That unfished recruitment and natural mortality change in concert both with the addition of the ORBS index and removal of all indices is not surprising. The base model hessian estimates a correlation between log(R0) and female natural mortality of `r dplyr::filter(mod_out$CoVar, label.i == 'SR_LN(R0)', label.j == 'NatM_uniform_Fem_GP_1') |> pull(corr) |> round(2)`.) Upweighting the \gls{s-wcgbt} by forcing the standard error of the log of the index to be 0.05 (compared to an average input value of `r mod_in$dat$CPUE |> dplyr::filter(index == 6) |> with(mean(se_log)) |> round(2)` in the base model) has the opposite effect of removing all indices (lower unfished recruitment, lower natural mortality, slightly higher unfished spawning output). Upweighting the WCGBTS also suggests that the peak in the combined hook and line index is slightly inconsistent with the peak in the \gls{s-wcgbt} index, and occurs approximately two years later than expected, given the selectivities estimated from the composition data associated with the two surveys. Notably, the run with the upweighted WCGBTS index has a problematic pattern in the early recruitment deviations, all of which are below zero, suggesting parameter estimates may be biased.

All other sensitivities to index data led to only minor changes during the estimation period. However, choice of recruitment index does influence the population forecast, particularly beginning around 2030. Including the RREAS index results in the highest absolute and relative spawning output during the forecast because the survey has been well above average since 2021. The SMURF index (base model), has the next highest forecast due to high observations in 2021 and 2023. A model with no recruitment index (no SMURF) is third highest. The model with the oceanographic index has the lowest forecast, though is only slightly lower than a model with no recruitment index. While the oceanographic index indicates higher recruitment in 2021 than in surrounding years, it predicts that the recruitment deviation is close to zero in 2021, and below average in all other years. The models with the RREAS and SMURF indices estimate that recruitment was well above average either for 2021-2024 (RREAS), or in 2021 and 2023 (SMURF). The RREAS index was not included in the base model because it did not appear correlated to recruitment for well-estimated year classes, and predicted high recruitment in years with not particularly notable year classes, while missing the large year classes in 2008 and 2010. The SMURF index is not long enough to compare to recruitment in any well-estimated years. (Exploratory 15-year retrospectives indicated year class strength stabilizes around age 10.) While the oceanographic index can be estimated as far back as WHEN (MEGAN?), recruitment deviation estimates through X were used to train the model, so comparing the index to recruitment estimates prior to X would be circular.

#### Modeling

Sensitivity to modeling assumptions is in @fig-model-sens-ssb and @fig-model-sens-depl and table Z.

A breakpoint natural mortality near the age at maturity and a shared natural mortality between males and females resulted in similar model results, with lower unfished recruitment, higher unfished spawning output, lower terminal year spawning output, and a relative terminal year spawning output below the management target. The likelihood for breakpoint natural mortality is 56 units worse than the base model with a similar number of parameters. The likelihood for a model with shared natural mortality is 59 likelihood units worse with one less parameter.

The model with time-varying weight length does not lead to changes in spawning output because spawning output is modeled as a function of length, not weight, but the time series of summary biomass does vary from the base model. Unfished summary biomass is lower than the base model and summary biomass also has more high-frequency variability during WCGBTS years when the weight-length relationship is changing. 

The model with non-linear density-dependent catchability for the WCGBTS improves the survey likelihood by about four units, worsens the age likelihood by about one unit, and improves the length likelihood by less than one unit. While the WCGBTS index fit is slightly better, the model still misses the overall pattern, indicating time-invariant density-dependent catchability alone cannot explain the conflict between composition and index data.

No other modeling sensitivities led to notable changes in population trajectories. However, we do note that estimating two sex-specific selectivity parameters for the recreational fleet improved the likelihood by 18 units. Estimating sex-specific selectivity for all fleets with sex data does improve the likelihood by an additional 28 units. However, this involves estimating 12 additional parameters, many of which seemed poorly estimated during earlier explorations.

<!-- Sensitivity to assumptions about model structure, i.e., model specification uncertainty.  -->

<!-- Sensitivity to data set choice (e.g., using emphasis factors to selectively remove data sources) and weighting schemes (e.g., MacAllister & Ianelli weighting versus Francis weighting vs. Dirichlet weighting for compositional data), which may also include a consideration of recent patterns in recruitment.  -->

#### Composition data

Sensitivity to use and treatment of composition data is in figures @fig-comp-sens-ssb and @fig-comp-sens-depl and table Z.

The McAllister \& Ianelli data weight method leads to a higher unfished recruitment, higher natural mortality, and higher somatic growth rate. This results in a higher unfished spawning output, much higher population peak in the 2000s, and a higher terminal year spawning output and relative spawning output. The lowpoint of the population in the 1980s and 1990s is also estimated to be larger.

Removing fishery lengths leads to a higher unfished spawning output, but similar terminal year spawning output, so a lower relative spawning output. Unfished recruitment is fairly similar but natural mortality is lower and the somatic growth rate is higher.

### Retrospective Analysis

The retrospective analysis showed little change in the population trajectory (@fig-retro1). 

Age 4+ abundance is used to compare among historical assessments (@fig-historical) due to different assumptions about maturity and fecundity that make spawning output and fraction unfished difficult to compare. Similar patterns of decline throughout the 1970s and 1980s are estimated among all previous among assessments although there were differences in estimated scale. The models conducted in 2005 and more recently have all estimated increases in the 2000s, but the timing of when the increase began has differed among assessments. The differences in age 4+ biomass between this assessment and that from 2017 are a low scale in the current assessment and a later recent peak in biomass (2019 rather than 2005). 

### Likelihood Profiles

<!-- Evaluation of model parameters. Likelihood profile for the base model over key parameters (typically natural morality, stock-recruit steepness, and equilibrium recruitment, or R0). The profile should indicate all likelihood values for individual components (e.g., indices by survey, compositional data for each type and fleet).   -->


TODO: add text here. Specifically reference the profile run with M fixed at the prior value (or as close as it got) instead of doing a separate sensitivity on that. Profiles are illustrated in figures @fig-r0-profile to @fig-h-profile-pars. Specific figures are @fig-r0-profile, @fig-r0-profile-pars, @fig-m-profile, @fig-m-profile-pars, @fig-h-profile, @fig-h-profile-pars.

## Unresolved Problems and Major Uncertainties

The composition data regularly include 30+ year-old fish, and support a medium-lived population. The likelihood profiles indicate the survey likelihood is maximized at a lower natural mortality than the estimated value. However, the \gls{s-wcgbt} index doubles and then halves again over a period of approximately five years, and the model is not able to fit this dynamic. Intuitively, a higher natural mortality could make the population more dynamic, so it is unclear why the survey likelihood is maximized at a lower natural mortality. The doubling could come from the large 2008 and, to a lesser extent, 2010 year classes, but the estimated recruitment deviation is not large enough to support the magnitude of the increase observed in the survey (and in observer catch rates on midwater trawl vessels). In addition, it is difficult for a population with relatively constant catches since 2017 and with individuals that regularly survive to 30+ years to have adult biomass decrease by approximately one-half over only two years (2019-2021). While changes in natural mortality could be possible, ocean conditions were relatively positive during those years (CITE ESR) and changes in natural mortality more often impact younger individuals. The large 2008 year class becomes less apparent in age-composition data in different years for the commercial fleet and the \gls{s-wcgbt}, and the mechanism for this "blurring" is unclear (several hypotheses: movement and selectivity changes, natural mortality, fishing mortality, increasing ageing error as the year class gets older, some combination). Overall, we were unable to find a reliable mechanistic way to simultaneously fit the survey and composition data; the candidate base model fits the composition data at the expense of the survey index. All data sources and the candidate base model indicate the population is at a more depleted state than it was in 2017 and than the 2017 assessment estimated the population was in 2017 (two distinct quantities). The magnitude of the change is less clear.

<!-- Describe any special issues (e.g., unbalanced or questionable data, missing survey data) that complicate scientific assessment, questions about the best model scenario. -->
