# Management

## Reference points

Reference points based on the biomass target of 40% of unfished spawning output, the spawners-per-recruit (SPR) target of 0.5, and the internal model estimate of maximum sustainable yield are shown in @tbl-ref-points-es and @fig-yield. 

## Harvest projections and decision tables

Harvest projections for the candidate base model assuming a P* of 0.45, sigma = 0.5, and the time-varying buffer are in @tbl-projections. After exploration of alternative axes of uncertainty during the review panel, the chosen axis of uncertainty was the parameter for equilibrium recruitment on a log scale: $\log(R_0)$.

The range of values was based on the following guidance in the terms of reference:

> One method bases uncertainty in management quantities for the decision table on the asymptotic standard deviation for the OFL in the final year of the model from the base model. Specifically, the current year spawning biomass for the high and low states of nature are given by the base model mean plus or minus 1.15 standard deviations (i.e., the 12.5th and 87.5th percentiles). A search across fixed values of lnR0 are then used to attain the current year spawning biomass values for the high and low states of nature.

The asymptotic standard deviation for the 2025 OFL from the base model was 0.186 and the point estimate of the 2025 OFL was 5440 mt. The associated 12.5th and 87.5th percentiles were 4392 mt and 6739 mt. Model runs from the likelihood profiles for $\log(R_0)$ which had OFL values which best matched these two values had $\log(R_0)$ = 10.25 and 10.75 relative to a base model estimate of 10.51.

### Assumed catches for 2025 and 2026

The Groundfish Management Team provided assumed catches for 2025 and 2026. 

The at-sea fleet used the full attainment of the at-sea set aside established in the [Pacific Coast Groundfish Fishery 2025-26 Harvest Specifications and Management Measures](https://www.pcouncil.org/documents/2024/05/f-6-attachment-2.pdf/#page=100) [Pacific Fishery Management Council, 2024, p. 100; @tbl-assumed_catch]. The full set-aside was assumed given the difficulty in predicting whether any single year will be a high-bycatch year.

The “Shorebased Commercial” fleet catch projection combined the following sectors: IFQ shorebased, Incidental, Non-Trawl Commercial, and Tribal shorebased (@tbl-assumed_catch). The projections for the IFQ shorebased sectors used the model projection under the high allocation scenario from the [2025-26 Harvest Specifications](https://www.pcouncil.org/documents/2024/07/2025-26-preferred-groundfish-harvest-specifications-and-management-measures-council-analytical-document.pdf/#page=107), because the actual 2025 allocation is closest to the high allocation scenario (Pacific Fishery Management Council, 2024, p. 107). For the Incidental sectors, the GMT used the total mortality (landings and discard mortality rates applied) 10-year maximum from the \gls{gemm} (23.4 mt in 2016) rounded to the nearest mt for both 2025 and 2026. This was also checked against the 2024 PacFIN scorecard (2.4 mt). The projections for the non-trawl commercial sectors used the maximum total mortality from the GEMM (9.5 mt in 2021) rounded to the nearest mt and added a buffer for uncertainty of 2 mt, which was the sample standard deviation for years 2018-2023 (excluding 2020). This projection was also checked against the 2024 PacFIN scorecard (7.2 mt). The GMT chose this projection because we expect to see a continued increase in midwater rockfish (including yellowtail rockfish) targeting among the non-trawl commercial fleet, since other species such as shortspine thornyhead and canary rockfish are constraining and since between 42° and 40° 10’ N. lat., non-bottom contact gear is the only option shoreward of 75 fathoms in Federal waters. 

For the Tribal shorebased sectors, the GMT used the GEMM to determine the average total mortality between 2018-2023, excluding 2020, which was 123.3 mt. While it is standard practice to project full attainment of Tribal set-asides and harvest targets (1000 mt for 2025-2026 in the [2025-2026 Harvest Specifications](https://www.pcouncil.org/documents/2024/07/2025-26-preferred-groundfish-harvest-specifications-and-management-measures-council-analytical-document.pdf/#page=103)), given the uncertainty in future fishery participation, delays in reporting, and market fluctuations, the GMT decided to add an uncertainty buffer to the 2018-2023 average mortality and project the catch as 350 mt for 2025 and 450 mt for 2026. These final values are closer to the 10-year maximum total mortality in the GEMM, which was 385.1 mt in 2015.

For the Washington and Oregon recreational fleets, the GMT used the maximum total mortality from the GEMM (87 and 83 mt in 2023, respectively) and Oregon’s recreational model projection, which predicts a total mortality of 93.4 mt for 2025 in Oregon. Since the GMT expects the recreational fleet to shift effort towards midwater rockfish, such as yellowtail rockfish, due to constrained canary rockfish limits, we chose to add a buffer for uncertainty, which resulted in a projection of 100 mt each for Washington and Oregon in both 2025 and 2026 (@tbl-assumed_catch). For the California fleet, the GMT chose to use the maximum total mortality in the GEMM (3.1 mt in 2023) since this added a sufficient uncertainty buffer when considering that the average total mortality between 2018-2023 (excluding 2020) was 1.5 mt and the 2024 PacFIN scorecard showed a total mortality of roughly 1 mt (@tbl-assumed_catch).

## Evaluation of scientific uncertainty

The model estimate of the coefficient of variation of the overfishing limit (OFL) in 2025 is `r round(mod_out$OFL_sigma, 3)`. This is less than the default SSC value of 0.5 for a category 1 assessment, so harvest projections assume an initial sigma of 0.5, and increase at a rate of 0.075 per year.

{{< pagebreak >}}

### Risk table

Below is a risk table for northern yellowtail rockfish to document 1) ecosystem and environmental factors, 2) stock assessment data inputs, and 3) assessment model fits and structural factors that could potentially affect stock productivity and/or uncertainty arising from the stock assessment (see text). Level 1 is favorable/less uncertain, Level 2 neutral, and Level 3 unfavorable/more uncertain

```{r, results = "asis"}
#| label: 
#| echo: false
#| warning: false

risk <-read.csv("Tables/RiskTable.csv") 
risk|>
  gt::gt() |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::cols_label(
    Ecosystem.and.environmental.conditions = "Ecosystem and environmental conditions",
    Assessment.data.inputs = "Assessment data inputs",
    Assessment.model.fits.and.structural.uncertainty = "Assessment model fits and structural uncertainty"
  ) |>
  gt::cols_width(
    everything() ~ px(200)
  ) |>
  gt::as_latex()

```

#### Ecosystem and environmental conditions{}

To identify ecosystem and environmental processes impacting northern yellowtail rockfish we evaluated recent trends in environmental drivers, focusing on the years after main recruitment deviations are estimated (2019 - 2025). We considered trends in environmental drivers of yellowtail recruitment, habitat and distribution, prey, competitors and predators, and the climate vulnerability assessment (CVA) by @mcclure2023. We did not consider non-fisheries human activities as none were identified to be applicable to yellowtail. Overall we consider ecosystem and environmental conditions to be neutral (Level 2) with medium to high confidence based on agreement between a majority of indicators, robust but uncertain evidence, and no apparent concerns. We use this, plus information related to the stock assessment, to fill out the ‘risk table’ in @tbl-risk, based on the framework outlined by the California Current Integrated Ecosystem Assessment (CCIEA) team [@Golden2024]. The ecosystem and environmnetal conditions discussed here were contributed by Megan Feddern, Isaac Kaplan, Nick Tolimieri, Chris Harvey and Jameal Samhouri.


##### Recruitment{}
La Niña conditions persisted from 2020 - 2022 but were followed by a strong El Niño in 2023 - 24, which caused warmer than average ocean temperatures that were particularly pronounced during the pelagic juvenile lifestage and which are negatively associated with yellowtail recruitment. Spring transition was substantially earlier than optimal for northern yellowtail in 2020 and later than optimal in 2022, but close to optimal in 2021, 2023 and 2024 based on the relationships described in Appendix A. Temperature exposure during egg incubation was above average in 2021 and 2023, indicating poor conditions, but average in 2024. Since 2019, longshore transport has been substantially above average during the pelagic juvenile lifestage indicating poor conditions for recruitment. 

The Washington nearshore rockfish survey in OCNMS [@Tolimieri2023; @Cope2023wa], which was updated through 2024 for this assessment, indicated an increase in the Black-yellowtail species complex from 2019 - 2021, low abundance in 2022 - 2023, and an increase in 2024. Similar patterns were observed based on the northern YOY rockfish index from the RREAS survey [@Gasbarro2025], with a more optimistic outlook of abundance in 2023. The coastwide RREAS index for yellowtail also indicated a strong YOY class in 2024 [@Field2021; @santora2021], but had less interannual variability from 2021 - 2023 (@fig-YOY). The collective evidence across oceanographic indices of recruitment and indices of juvenile abundance indicates recruitment was average or below the long-term average over the last 5 years with the exception of 2021.

Overall, based on the collective evidence recruitment is characterized as neutral to unfavorable conditions with robust evidence. 

##### Distribution and habitat{}
Young of the year yellowtail rockfish settle to nearshore areas and are known to utilize kelp bed habitat. Giant and bull kelp abundance based on the Kelp Watch Report Card remain close to the historical average in Washington [@Bell2023]. However, Oregon bull kelp cover is low, and is estimated to be at only 39% of historical levels, and over the last five years cover has been at only 19% of historical levels. Kelp abundance in California regions is also low relative to the historical mean. @Tolimieri2020 and @Taylor_petrale_2023 used spatio-temporal models to examine the distribution and abundance of groundfish along the West Coast. We considered updated spatio-temporal models for young (less than 4.5 years) and adult yellowtail rockfish, separately. These models indicate no changes in distribution. Collectively, habitat and distribution information indicate neutral to somewhat unfavorable conditions due to low kelp cover in Oregon. 

##### Prey{}

Overall, most available evidence suggests adequate forage for yellowtail in 2024 and recent years and is characterized as neutral to favorable. The CCIEA RREAS euphausiid (krill) indicator shows an increasing trend in the central Central California Current over the last five years, including 2024 (@Leising2025; see Figure I.2). RREAS data for 42 - 46 degrees N indicates no strong trend over the last five years, and krill abundance and size from the Trinidad Head Line were near average for most of 2024. Herring abundance sampled by JSOES  in the Northern California Current has been stable in recent years, although the 2023 acoustic survey estimates of coastwide herring abundance suggest a decline from 2019 levels  [@stierhoff2024distribution]. Production of juvenile hake was estimated in the stock assessment to be above average in 2020 and 2021, though there is high uncertainty in the stock assessment estimates of recruitment for more recent years [@Johnson2025]. Copepods are found in diets of juvenile yellowtail, and sampling at the Newport Hydrographic Line (@Leising2025; see Figure 3.1) suggested average feeding conditions over the last 5 years, with improvements once El Niño conditions waned in early 2024. We note that the coastwide krill abundance index, derived from acoustic data, was not available in 2024, but the 2023 values for this index were the 2nd lowest since the beginning of sampling in 2007.

##### Predators and competitors{}

Predators that impose the largest amounts of predation mortality on yellowtail rockfish were identified from Ecopath food web modeling. The Ecopath models of @field2006top and @koehn2016 were recently revised (C.  Best-Otubu, P.Y. Hernvann, N. Lezama Ochoa, I. Kaplan). The highest sources of predation mortality on yellowtail rockfish, from greatest to least, derive from seven predators: California sea lions, lingcod, porpoises, fur seals, harbor seals, sablefish and skates. Based on changes in abundance over the last 5 years, six of the seven main predators are unlikely to drive any changes in predation over the last 5 years [@Caretta2024; @Taylor2019; @Gertseva2019; @Taylor2021]. One predator, sablefish, may have imposed some increased predation pressure on the ecosystem [@Johnson2023], but the linkage to yellowtail specifically is very uncertain. Similarly, we considered hake as a potential competitor for krill, however the lack of evidence of krill being a limiting prey source for yellowtail and lack of direct evidence of competition makes this link highly uncertain. Overall, we scored predation and competition effects  as neutral, with some uncertainty.

##### Climate vulnerability assessment{}

@mcclure2023 found that yellowtail rockfish had a climate vulnerability of moderate/high and an overall climate exposure of high, due largely to potential impacts from ocean acidification on prey (ranked very high) and mean sea surface temperature (ranked high). We consider the effects of temperature and prey availability to be well informed in other sections of this risk table and the assessment and as a result the CVA ranking was not included in our final scoring of the ecosystem and environmental considerations.

## Regional management considerations

Currently yellowtail rockfish is managed with distinct harvest specifications north and south of $40^\circ 10'$ N. latitude. This assessment aligns with the entire northern stock and therefore does not provide a recommended method for allocating harvests at a finer regional scale. Current genetic, oceanographic, and life history evidence indicates a single break in the population around Cape Mendocino, near $40^\circ 10'$ N. latitude.

## Research and data needs

### Response to recommendations in previous assessment

-   A problem common to assessments of all stocks caught in the midwater is the lack of a targeting survey
    -   This is still an outstanding issue. This assessment explores inclusion of a new hook and line survey.
-   Research to determine whether old females of a variety of rockfish species actually have a mortality rate different than that of younger females. Assessments variously treat the discrepancies seen in sex ratios of older fish as either mortality-related or due unavailability to the fishery (e.g., ontogenetic movement offshore, or to rockier habitats). As these assumptions impact model outcomes very differently, resolving this issue would greatly improve confidence in the assessments.
    -   This assessment includes a number of sensitivities related to this, as well as deeper exploration of data patterns outside of the assessment model to support modeling choices.
-   A hindrance to analysis of the commercial fishery is the inability to distinguish between midwater and trawl gear, particularly in data from the 1980s-1990s. Reliable recording of gear type will ensure that this does not continue to be problematic for future assessments.
    -   In years where midwater and bottom trawl gear are differentiated in PacFIN, exploratory data analysis indicated there is essentially no difference in the age and size compositions of fish caught. Thus, combining midwater and bottom trawl gear into a single model fleet seemed appropriate, and there is no need to reconstruct the historical ratio of catches between the two gears. We agree they should continue to be differentiated in ongoing sampling programs.
-   A commercial index in the North. This is by far the largest segment of the fishery, and the introduction of the trawl rationalization program should mean that an index can be developed for the current fishery when the next full assessment is performed.
    -   This was explored as a sensitivity
-   Further investigation into an index for the commercial logbook dataset from earlier periods.
    -   This was not done. A new fishery-independent hook and line index and a number of indices of recruitment were explored instead.
-   Further analysis of growth patterns along the Northern coast. The previous full assessment subdivided the Northern stock based on research showing differential growth along the coast, and although data for the assessment is no longer available along the INPFC areas used in that analysis, there may be some evidence of growth variability that would be useful to include in a future assessment.
    -   While growth may be different above and below Cape Mendocino, we found no evidence for spatial variability in size-at-age in the area north of $40^\circ 10'$.

### New recommendations

While all of the following recommendations would improve the assessment, they are listed roughly in order of importance:

1.  Explore catchability and selectivity of the bottom trawl survey using existing data streams. No new midwater surveys have begun in the last eight years, and the likelihood of new surveys in future years is low, so recommending new surveys is an unproductive recommendation, and other options should be explored. The STAT understands that the WCGBTS has collected echosounder data over the years which has not been analyzed to date. Analyzing this data and exploring the relationship between acoustic data and sampled biomass from the bottom trawl gear will help understand potential variability in catchability. Identifying drivers of bottom trawl catchability (e.g., environmental drivers, density-dependence and/or schooling behavior) would be useful for all midwater species, not just Yellowtail rockfish (e.g., Canary and Widow rockfish). More sophisticated comparisons between CPUE in the catch share commercial midwater trawl sector and the bottom trawl survey could also be fruitful.

2. This assessment explored a number of new sources of data to provide and index of early life history survival years before yellowtail recruit to more traditional forms of population sampling. Ultimately, we chose to include the SMURF index in the base model. However, future research could more formally validate these indices and potentially use ensemble modeling to facilitate the inclusion of multiple different data sources on early life history into a single index in the model. A transition to a modeling framework that permits modeling of random effects (e.g., WHAM) may help facilitate this effort.

3.  Age data is the only source of sex-specific recreational composition data, and it provided important information about selectivity of the fleet and patterns of sex ratio by age. Continued collection of recreational age data from Washington and new collections from Oregon should be prioritized, and could support a transition to an empirical weight-at-age model in the future.

4.  The oceanographic index is an externally estimated regression trained on estimated recruitment deviations from a near-to-final base model. Therefore, using the index to predict recruitment deviations in years that it was trained on is circular and ill-advised. We only included the oceanographic index for years *not* included in the training data, but this meant that the years for which the index *was* included in the sensitivity model had no other data informing recruitment that could help estimate the scaling factor for the index (i.e., catchability). We fixed catchability at one in the sensitivity, since in theory the index should predict absolute recruitment deviations, but this is a strong assumption. A process that uses raw oceanographic data directly in the assessment, instead of predictions from a regression on historical recruitment deviations, could avoid this. As above, such an exercise is likely easier in an assessment platform that permits estimation of random effects (e.g., WHAM).

5.  The biological population extends into British Columbia, but no data from Canada is included in this model. Better understanding of transboundary population dynamics would improve management.

6.  The combined hook and line survey catches smaller, and presumably younger fish, than the trawl surveys and fishing fleets, so can provide leading information about incoming year class strength. However, the fits to the length data are not very good. The recreational length composition data have a similarly shaped distribution, and adding sex-specific selectivity greatly improved the fit to recreational data. However, sex-specific selectivity was not estimable for the hook and line survey, likely because there is no sex data. Collecting sex and age data from the hook and line survey could allow for better estimation of selectivity and a more informative survey.
