# Tables 

## Data
```{r} 
#| label: 'set-rda-dir-tbls'
#| echo: false
#| warning: false
#| eval: true
#| include: false
library(tidyr)
library(gt)
```

<!-- Fishery Dependent Data -->

::: {.landscape}
```{r}
#| label: tbl-all_removals
#| echo: false
#| warning: false
#| tbl-cap: "Total removals (mt) of yellowtail rockfish for the commercial (Com.), foreign (For.), at-sea hake (ASHOP), and recreational (Rec.) fleets used in the assessment model."


CatchTable <- read.csv("Tables/CatchTable.csv")%>%
select(-ComModelTotal)
CatchTable[is.na(CatchTable)] <- 0
CatchTable |>
  gt() |>
 cols_label(
    year = "Year",
    ComWA = "Com. WA",
    ComOR = "Com. OR",
    ComCA = "Com. CA",
    ComDiscards = "Com. Discards",
    Foreign = "For.",
    RecWA = "Rec. WA",
    RecOR = "Rec. OR",
    RecCA = "Rec. CA",
  ) |> 
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()

```
:::
{{< pagebreak >}}

```{r}
#| label: tbl-comm_lengths
#| echo: false
#| warning: false
#| tbl-cap: "Summary of the number of length samples and trips for  for California (CA), Oregon (OR), and Washington (WA) commercial fishery."


commlengths <- read.csv("Tables/pacfin_lengths.csv") 
commlengths|>
  gt() |>
  tab_options(
    table.font.size = 11,
    latex.use_longtable = TRUE
  ) |>
cols_label(
    year = "Year",
    CA.n_fish = "N Lengths \n (CA)",
    CA.n_trip = "N Trips \n (CA)",
    OR.n_fish = "N Lengths \n (OR)",
    OR.n_trip = "N Trips \n (OR)",
    WA.n_fish = "N Lengths \n (WA)",
    WA.n_trip = "N Trips \n (WA)",
    input_n = "N Input"
  ) |>
  as_latex()
```
{{< pagebreak >}}
```{r}
#| label: tbl-comm_ages
#| echo: false
#| warning: false
#| tbl-cap: "Summary of the number of age samples and trips for  for California (CA), Oregon (OR), and Washington (WA) commercial fishery."


commages <-read.csv("Tables/pacfin_ages.csv") 
commages|>
  gt() |>
  tab_options(
    table.font.size = 11,
    latex.use_longtable = TRUE
  ) |>
 cols_label(
    year = "Year",
    CA.n_fish = "N Ages \n (CA)",
    CA.n_trip = "N Trips \n (CA)",
    OR.n_fish = "N Ages \n (OR)",
    OR.n_trip = "N Trips \n (OR)",
    WA.n_fish = "N Ages \n (WA)",
    WA.n_trip = "N Trips \n (WA)",
    input_n = "N Input"
  ) |>
  as_latex()
```
{{< pagebreak >}}
```{r}
#| label: tbl-ashop_comps
#| echo: false
#| warning: false
#| tbl-cap: "Summary of the number of age  and length samples and trips for the at-sea hake fishery"

ashop_comp <- read.csv("Tables/ashop_comps.csv") 
ashop_comp |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  cols_label(
    ntow.length = "Lengths (n tows)",
    nfish.length = "Lengths (n fish)",
    ntow.age = "Ages (n tows)",
    nfish.age = "Ages (n fish)",
  ) |>
  as_latex()
```
{{< pagebreak >}}
```{r, rec_bio}
#| label: tbl-rec-bio
#| echo: false
#| warning: false
#| tbl-cap: "Sample sizes for age and length samples from the recreational fishery."

rec_bio_table <- read.csv("../Data/Processed/rec_bio_sample_size_table.csv", check.names = FALSE)
rec_bio_table |> 
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

{{< pagebreak >}}

```{r, tbl-wcgbts-index}
#| label: tbl-wcgbts-index
#| echo: false
#| warning: false
#| tbl-cap: "Index of abundance and log-scale standard errors for the WCGBTS."

mod_out$cpue |>
    dplyr::filter(grepl("WCGBTS", Fleet_name)) |>
    dplyr::select(Yr, Obs, SE_input) |>
    gt() |>
    cols_label(
        Yr = "Year",
        Obs = "Observed",
        SE_input = "Std. Error"
    ) |>
    tab_options(
        table.font.size = 12,
        latex.use_longtable = TRUE
    ) |>
    as_latex()

```

```{r, tbl-tri-index}
#| label: tbl-tri-index
#| echo: false
#| warning: false
#| tbl-cap: "Index of abundance and log-scale standard errors for the Triennial survey."

mod_out$cpue |>
    dplyr::filter(grepl("Tri", Fleet_name)) |>
    dplyr::select(Yr, Obs, SE_input) |>
    gt() |>
    cols_label(
        Yr = "Year",
        Obs = "Observed",
        SE_input = "Std. Error"
    ) |>
    tab_options(
        table.font.size = 12,
        latex.use_longtable = TRUE
    ) |>
    as_latex()

```
{{< pagebreak >}}
```{r, tbl-wcgbts-bio}
#| label: tbl-wcgbts-bio
#| echo: false
#| warning: false
#| tbl-cap: "Sample sizes for the age and length compositions from the WCGBTS. The ages are treated as conditioned on length and use the number of fish (within each length bin) as the input sample size."

wcgbts_bio_table <- read.csv("../Data/Processed/input_n_wcgbts.csv", check.names = FALSE)
wcgbts_bio_table |> 
  gt() |>
  cols_label(
    year = "Year",
    n_ages = "N. ages",
    n_tows = "N. tows",
    n_lengths = "N. lengths",
    input_n = "Input N."
  ) |> 
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

```{r, tbl-tri-bio}
#| label: tbl-tri-bio
#| echo: false
#| warning: false
#| tbl-cap: "Sample sizes for the marginal age and length compositions from the Triennial survey."

tri_bio_table <- read.csv("../Data/Processed/input_n_tri.csv", check.names = FALSE)
tri_bio_table[is.na(tri_bio_table)] <- 0
tri_bio_table |> 
  gt() |>
    cols_label(
    year = "Year",
    n_tows_ages = "N. tows with ages",
    n_ages = "N. ages",
    input_n_ages = "Input N. for ages",
    n_tows_lengths = "N. tows with lengths",
    n_lengths = "N. lengths",
    input_n_lengths = "Input N. for lengths"
  ) |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()

```

<!--Indices tables -->

```{r}
#| label: tbl-hl_percent_pos
#| echo: false
#| warning: false
#| tbl-cap: "Summary of percent positive by number of trips for the combined OR-WA hook and line survey"


percposHL <- read.csv("Tables/HL_yellowtail_percent_pos.csv") 
percposHL|>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

{{< pagebreak >}}
:::{.landscape}
```{r, hl_mod_slx}
#| label: tbl-hl_mod_slx
#| echo: false
#| warning: false
#| tbl-cap: "Summary of model selection for the combined OR-WA hook and line survey"


modslxHL <- read.csv("Tables/HL_yellowtail_model_selection.csv") 
modslxHL[is.na(modslxHL)] <- '-'
modslxHL|>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```
:::
{{< pagebreak >}}

```{r}
#| label: tbl-hl_index
#| echo: false
#| warning: false
#| tbl-cap: "The final index for the combined OR-WA hook and line survey"


HLindex <- read.csv("Tables/HL_index_forSS.csv")%>%select(-c(month, fleet)) 
HLindex|>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

```{r, orbs_perc_pos}
#| label: tbl-percent_pos
#| echo: false
#| warning: false
#| tbl-cap: "Summary of trips from ORBS dockside sampling from ODFW"


read.csv("Tables/yellowtail_percent_pos.csv") |> 
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

{{< pagebreak >}}

::: {.landscape}
<!-- Needs Alt text -->
```{r}
#| label: tbl-orbs_mod_select
#| echo: false
#| warning: false
#| tbl-cap: "Model selection for top ten covariate combinations considered for the ORBS index"

orbs_modselect <- read.csv("Tables/yellowtail_model_selection.csv")[1:10, ]
orbs_modselect[orbs_modselect == "Included"] <- "Incl."
orbs_modselect[is.na(orbs_modselect)] <- '-'
orbs_modselect |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

:::

{{< pagebreak >}}
<!-- Needs Alt text -->
```{r}
#| label: tbl-orbs_index
#| echo: false
#| warning: false
#| tbl-cap: "Relative index of abundance from ORBS dockside sampling from ODFW."

read.csv("Tables/index_forreport_ORBS.csv") |> 
  dplyr::mutate(dplyr::across(-1, round, 3)) |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```
<!-- Needs Alt text -->
```{r}
#| label: tbl-smurf_mod_select
#| echo: false
#| warning: false
#| tbl-cap: "Model selection for covariate combinations considered for the SMURF YOY index"

smurf_modselect <- read.csv("Tables/SMURF_model_selection.csv")
smurf_modselect[smurf_modselect == "Included"] <- "Incl."
smurf_modselect |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```
<!-- Needs Alt text -->
```{r}
#| label: tbl-smurf_index
#| echo: false
#| warning: false
#| tbl-cap: "Relative index of abundance from SMURF YOY index."

smurf_in <- read.csv("Tables/SMURF_index.csv")
smurf_in |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```


```{r}
#| label: tbl-consider
#| echo: false
#| warning: false
#| tbl-cap: "Comparison of potential age-0 abundance and recruitment indices by data sourse"


comp <-read.csv("Tables/YOYComparison.csv") 
comp|>
  gt::gt() |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::cols_label(
    Recruitment...Age.0.abundance.index = "Recruitment / Age-0 abundance index"
  )|>
  gt::cols_width(
    everything() ~ px(200)
  ) |>
  gt::as_latex()
```



## Model results
 
```{r}
#| label: tbl-model-config
#| warning: false
#| echo: false
#| tbl-cap: !expr if(eval_tables) config_cap

config_table |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```


```{r}
#| label: tbl-n-param
#| warning: false
#| echo: false
#| tbl-cap: !expr if(eval_tables) parcount_cap

parcount_table |>
  dplyr::filter(Count > 0) |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

::: {.landscape}

```{r}
#| label: tbl-pars
#| warning: false
#| echo: false
#| tbl-cap: !expr if(eval_tables) pars_cap

pars_table |>
  mutate(SD = ifelse(Status == 'fixed', NA, SD)) |>
  gt() |>
  sub_missing(missing_text = '') |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```
:::


```{r}
#| label: tbl-compweight
#| warning: false
#| echo: false
#| tbl-cap: !expr if(eval_tables) compweight_cap

compweight_table |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

```{r, results = "asis"}
#| label: tbl-ts
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) time_series_cap 
#| tbl-pos: H

time_series_table |>
kableExtra::kable(
  format = "latex", 
  longtable = TRUE,
  booktabs = TRUE,
  caption = "Time series of population estimates from the base model.",
  linesep = "") |>
  kableExtra::kable_styling(
    latex_options = "repeat_header",
    font_size = 8) |>
  kableExtra::column_spec(
    column = 1:9,
    width = "0.5in"
  )
```


## Management

\pagebreak

::: {.landscape}

```{r, results = "asis"}
#| label: tbl-projections
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) projections_cap 
#| tbl-pos: H

projections_table |>
  gt::gt() |>
  gt::fmt_number(
    columns = c(2:5, 7:9),
    decimals = 0
  ) |>
  gt::fmt_number(
    columns = c(6, 10),
    decimals = 3
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE 
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "---"
  ) |>
  gt::cols_align(
    align = "center"
  ) |>
  gt::cols_width(
    tidyselect::everything() ~ px(75)
  ) |>
  gt::as_latex()

```

\pagebreak


```{r}
#| label: tbl-sens-indices
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: "Differences in negative log-likelihood, estimates of key parameters, and estimates of derived quantities between the base model and several alternative models (columns). See main text for details on each sensitivity analysis. Red values indicate negative log-likelihoods that were lower (fit better to that component) than the base model."
#| tbl-pos: H
table_sens(here::here("report/Figures/sensitivities/indices_table.csv"))
``` 

{{< pagebreak >}}

```{r}
#| label: tbl-sens-modeling
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: "Differences in negative log-likelihood, estimates of key parameters, and estimates of derived quantities between the base model and several alternative models (columns). See main text for details on each sensitivity analysis. Red values indicate negative log-likelihoods that were lower (fit better to that component) than the base model."
#| tbl-pos: H
table_sens(here::here("report/Figures/sensitivities/modeling_table.csv"))

``` 

{{< pagebreak >}}


```{r}
#| label: tbl-sens-comp_data
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: "Differences in negative log-likelihood, estimates of key parameters, and estimates of derived quantities between the base model and several alternative models (columns). See main text for details on each sensitivity analysis. Red values indicate negative log-likelihoods that were lower (fit better to that component) than the base model."
#| tbl-pos: H
table_sens(here::here("report/Figures/sensitivities/comp_data_table.csv"))

``` 

:::
