# code to set base model directory and update r4ss plots and tables as needed

# location of base model (TODO: change as needed)
# path is relative to /report/
mod_loc <- "../Model_Runs/3.10_exp_comps_2024"

# read model output using r4ss
cli::cli_alert_info("Reading model output")
model <- r4ss::SS_output(
  dir = mod_loc,
  SpawnOutputLabel = "Spawning output (trillions of eggs)",
  printstats = FALSE,
  verbose = FALSE
)

# make new r4ss plots if the old files don't exist
# or are associated with an older model
# path is relative to /report/
make_plots <- FALSE
if (file.exists("r4ss_plots/_SS_output.html")) {
  html_lines <- readr::read_lines("r4ss_plots/_SS_output.html")
  if (!grepl(
    pattern = html_lines[grep("Starting time of model:", html_lines) + 1] |>
      gsub(pattern = "</p>", replacement = ""),
    x = model$StartTime
  )) {
    make_plots <- TRUE
  }
} else {
  make_plots <- TRUE
}

if (make_plots) {
  # make r4ss plots
  cli::cli_alert_info("Making new r4ss plots")
  # path to r4ss plots is relative to the model directory
  r4ss::SS_plots(model, printfolder = "../../report/r4ss_plots")
}

# make new exec summary latex tables if the old files don't exist
# or are associated with an older model
make_tables <- FALSE
if (!dir.exists("tex_tables")) {
  dir.create("tex_tables")
  make_tables <- TRUE
}
if (file.exists("tex_tables/README.md")) {
  tex_table_lines <- readr::read_lines("tex_tables/README.md")
  if (!grepl(
    pattern = tex_table_lines[5],
    x = model$StartTime
  )) {
    make_tables <- TRUE
  }
} else {
  make_tables <- TRUE
}

if (make_tables) {
  # make new exec summary latex tables
  cli::cli_alert_info("Making new exec summary latex tables")
  # create CSV files for exec summary tables
  r4ss::SSexecutivesummary(replist = model)
  # convert the tables to LaTeX format
  tex_tables <- sa4ss::es_table_tex(
    dir = model$inputs$dir,
    save_loc = "tex_tables"
  )
  readr::write_lines(
    x = c(
      "# README for tex_tables",
      "The .tex files in this directory are generated by sa4ss::es_table_tex()",
      "which is called from the /report/custom_code.R script.",
      "Model start time is:",
      model$StartTime
    ),
    file = "tex_tables/README.md"
  )
}
