---
title: "Alternative projection for Yellowtail rockfish"
author: "Kiva L. Oken" 
affiliation: 'NOAA Fisheries Northwest Fisheries Science Center, 2725 Montlake Blvd E, Seattle, WA 98112'
date: today
format:
  pdf:
    template: catch_only_projection_template.tex
execute:
  echo: false
params:
  species: "yellowtail rockfish"
  assess_year: 2025
  current_year: 2025
  final_proj_year: 2036
  category: 1
  sigma: 0.5
  p_star: 0.45
  spawn_output_decimals: 2
  spawn_output_units: "(trillions of eggs)"
  base_mod: "model_runs/5.09_no_extra_se"
  new_mod: "model_runs/5.12_adj_hcr2"
---

```{r}
#| label: get-params
#| message: false

library(r4ss)
library(here)
library(dplyr)

species <- params$species
Species <- stringr::str_to_sentence(params$species)
assess_year <- params$assess_year
current_year <- params$current_year
final_proj_year <- params$final_proj_year
category <- params$category
sigma <- params$sigma
p_star <- params$p_star
spawn_output_decimals <- params$spawn_output_decimals

base_mod <- params$base_mod 
model_original <- SS_output(here(base_mod), verbose = FALSE, printstats = FALSE)
new_mod <- params$new_mod
model <- SS_output(here(new_mod), verbose = FALSE, printstats = FALSE)

# define ranges of years to get values
all_years <- assess_year:final_proj_year
proj_years <- (current_year + 2):final_proj_year
catch_years <- assess_year:(assess_year + 1)
alt_years <- (assess_year + 2):(assess_year + 3)

```

```{r}
#| label: modify-projection
#| eval: false

# modify projection

mod_in <- SS_read(here('model_runs', base_mod))

ofl_2027 <- model_original$derived_quants |> 
  filter(grepl('OFLCatch_2027', Label)) |> 
  pull(Value)

buffer_2028 <- PEPtools::get_buffer(years = 2025:2028, sigma = 0.5, pstar = 0.45, verbose = FALSE)[4, 'buffer']

# set buffer for 2027
mod_in$fore$Flimitfraction_m[3, 'fraction'] <- (ofl_2027-1) / ofl_2027
# set buffer for 2028
mod_in$fore$Flimitfraction_m[4, 'fraction'] <- mean(c(1, buffer_2028))

# SS_write(mod_in, here('Model_Runs/5.11_adj_hcr'), overwrite = TRUE)

mod2 <- SS_read(here('Model_Runs/5.11_adj_hcr'))
mod2$fore$FirstYear_for_caps_and_allocations <- 2029
mod2$fore$Flimitfraction_m[3:4, 'fraction'] <- 1
new_fixed_catches <- r4ss::SS_ForeCatch(model_original) |>
  rename(year = `#Year`) |> 
  filter(year %in% 2027:2028) |>
  group_by(year) |>
  mutate(pct = `dead(B)` / sum(`dead(B)`),
         total2027 = 5050,
         total2028 = 4730,
         total = ifelse(year == 2027, total2027, total2028),
         catch_or_F = pct * total) |>
  select(year, seas = Seas, fleet = Fleet, catch_or_F)
mod2$fore$ForeCatch <- bind_rows(mod_in$fore$ForeCatch, new_fixed_catches)
# SS_write(mod2, here('Model_Runs/5.12_adj_hcr2'), overwrite = TRUE)

```

```{r}
#| label: calc-table
#| echo: false
#| warning: false
#| message: false

# function to get model outputs
catch_only_projection_table <- function(model, all_years, proj_years, catch_years) {
    # get realized catch from model output
    catch <- model$derived_quants |>
        dplyr::filter(Label %in% paste0("ForeCatch_", catch_years)) |>
        dplyr::reframe(
            Year = stringr::str_extract(Label, "\\d+") |> as.numeric(),
            Catch = Value
        )
    ofl <- model$derived_quants |>
        dplyr::filter(Label %in% paste0("OFLCatch_", proj_years)) |>
        dplyr::reframe(
            Year = stringr::str_extract(Label, "\\d+") |> as.numeric(),
            OFL = Value
        )
    acl <- model$derived_quants |>
        dplyr::filter(Label %in% paste0("ForeCatch_", proj_years)) |>
        dplyr::reframe(
            Year = stringr::str_extract(Label, "\\d+") |> as.numeric(),
            ACL = Value
        )
    sb <- model$derived_quants |>
        dplyr::filter(Label %in% paste0("SSB_", all_years)) |>
        dplyr::reframe(
            Year = stringr::str_extract(Label, "\\d+") |> as.numeric(),
            SB = Value
        )
    status <- model$derived_quants |>
        dplyr::filter(Label %in% paste0("Bratio_", all_years)) |>
        dplyr::reframe(
            Year = stringr::str_extract(Label, "\\d+") |> as.numeric(),
            status = round(Value, 3)
        )

    # get buffer from PEPtools function
    Buffer <- PEPtools::get_buffer(
        years = all_years, sigma = sigma, pstar = p_star,
        verbose = FALSE
    ) |>
        dplyr::rename(Year = year, Buffer = buffer) |>
        dplyr::filter(Year %in% proj_years)

    # combine all the tables above (joined by year)
    table <- purrr::reduce(
        list(ofl, Buffer, acl, sb, status, catch),
        ~ dplyr::full_join(.x, .y, by = "Year")
    ) |>
        dplyr::arrange(Year) |>
        dplyr::relocate(Catch, .after = Year) |>
        dplyr::mutate(
            Buffer_from_ratio = dplyr::case_when(
                status >= model$btarg ~ round(ACL / OFL, 3),
                .default = NA # ratio doesn't work for years with 40-10 adjustment
            ),
            .after = Buffer
        ) |>
        dplyr::mutate(
            ABC = Buffer * OFL,
            .after = Buffer_from_ratio
        ) |>
        dplyr::rename(
            `Actual & Assumed Removals` = Catch,
            `Stock Status` = status,
            `Spawning Output` = SB,
        )
}

# function to apply gt formatting to the table
format_table <- function(table) {
    table |>
        gt::gt() |>
        gt::fmt_number(
            columns = tidyselect::starts_with("Actual") | tidyselect::starts_with("OFL") | tidyselect::starts_with("ABC") | tidyselect::starts_with("ACL"),
            decimals = 0
        ) |>
        gt::fmt_number(
            columns = tidyselect::contains("Spawning"),
            decimals = spawn_output_decimals
        ) |>
        gt::tab_options(
            table.font.size = 11, # reduced font size
            latex.use_longtable = TRUE
        ) |>
        gt::sub_missing(
            columns = tidyselect::everything(),
            missing_text = "---"
        ) |>
        gt::cols_align(
            align = "center"
        ) |>
        gt::cols_width(
            everything() ~ px(65)
        ) |>
        gt::data_color(
            columns = !c(tidyselect::contains('HCR'),
                         tidyselect::matches('Year'),
                         tidyselect::matches('Buffer')),
            palette = "gray90",
            na_color = "gray90"
        ) |>
        gt::as_latex()
}
```

```{r}
#| label: warning-about-buffer
#| echo: false
#| warning: true
#| message: true

table_original <- catch_only_projection_table(model_original,
    all_years = head(all_years, 12), proj_years = proj_years, catch_years = catch_years
) |>
  select(-`Spawning Output`)

table <- catch_only_projection_table(model,
    all_years = all_years, proj_years = proj_years, catch_years = catch_years
) |>
  select(-`Actual & Assumed Removals`, -Buffer) |>
  mutate(ABC = ifelse(Year %in% alt_years, ACL, ABC)) |> # overwrite externally calculated ABC for alternative HCR years
  rename_with(~ paste(.x, "(yyyy)"), .cols = -Year)

# combine the two tables
wide_table3 <- dplyr::full_join(
  table,
  table_original,
  by = "Year"
) |>
  dplyr::select(
    Year,
    OFL, `OFL (yyyy)`,
    `Buffer`,
    ABC, `ABC (yyyy)`,
    `Actual & Assumed Removals`,
    ACL, `ACL (yyyy)`,
    `Spawning Output (yyyy)`,
    `Stock Status`, `Stock Status (yyyy)`
  ) |>
  dplyr::rename_with(.fn = function(x) {
    gsub("yyyy", 'alt HCR', x)
  }) 

table_cap <- glue::glue("Adopted {assess_year} benchmark assessment projection and projection with an alternative HCR for {alt_years[1]} and {alt_years[2]}. Table includes OFLs (mt), buffer for the alternative HCR, ABCs (mt), actual & assumed catch (mt), ACLs (mt), and stock status (fraction of unfished spawning output) given the removals. The gray shading indicates values associated with the proposed alternative HCR. For {assess_year + 4} and beyond, the default HCR with 40-10 rule and P* of {p_star} is assumed")
```

<!-- ::: {.landscape} -->

```{r}
#| label: tbl-proj
#| echo: false
#| warning: false
#| message: false
#| eval: true
#| tbl-cap: !expr table_cap
format_table(wide_table3)
```

